        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE ALLOCATE_GU_USE__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_GU_USE
            END SUBROUTINE ALLOCATE_GU_USE
          END INTERFACE 
        END MODULE ALLOCATE_GU_USE__genmod
