        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE ALLOCATE_BOUND_GEOMGU__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_BOUND_GEOMGU(B,INPANEL)
              USE PGMOD
              TYPE (TBOUND) :: B
              INTEGER(KIND=4) :: INPANEL
            END SUBROUTINE ALLOCATE_BOUND_GEOMGU
          END INTERFACE 
        END MODULE ALLOCATE_BOUND_GEOMGU__genmod
