        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE ALLOCATE_BOUND_COLLOCATE_POINTS__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_BOUND_COLLOCATE_POINTS(IA,INCP)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: INCP
            END SUBROUTINE ALLOCATE_BOUND_COLLOCATE_POINTS
          END INTERFACE 
        END MODULE ALLOCATE_BOUND_COLLOCATE_POINTS__genmod
