        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE ALLOCATE_BOUNDLINE_GEOM2__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_BOUNDLINE_GEOM2(IBNDL)
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE ALLOCATE_BOUNDLINE_GEOM2
          END INTERFACE 
        END MODULE ALLOCATE_BOUNDLINE_GEOM2__genmod
