        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 13 11:10:58 2025
        MODULE AREA_QUADRILATERAL__genmod
          INTERFACE 
            FUNCTION AREA_QUADRILATERAL(Z1,Z2,Z3,Z4)
              COMPLEX(KIND=8) :: Z1
              COMPLEX(KIND=8) :: Z2
              COMPLEX(KIND=8) :: Z3
              COMPLEX(KIND=8) :: Z4
              REAL(KIND=8) :: AREA_QUADRILATERAL
            END FUNCTION AREA_QUADRILATERAL
          END INTERFACE 
        END MODULE AREA_QUADRILATERAL__genmod
