        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:14 2024
        MODULE BIND_AREACONST__genmod
          INTERFACE 
            SUBROUTINE BIND_AREACONST(K)
              INTEGER(KIND=4) :: K
            END SUBROUTINE BIND_AREACONST
          END INTERFACE 
        END MODULE BIND_AREACONST__genmod
