        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:05 2024
        MODULE BM_DEALLOCATE_SPARSE_MROWS__genmod
          INTERFACE 
            SUBROUTINE BM_DEALLOCATE_SPARSE_MROWS(SPARSE)
              USE SLAU_BLOCK
              TYPE (SPARSE_MATRIX) :: SPARSE
            END SUBROUTINE BM_DEALLOCATE_SPARSE_MROWS
          END INTERFACE 
        END MODULE BM_DEALLOCATE_SPARSE_MROWS__genmod
