        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:05 2024
        MODULE BM_INIT_BLOCK_R2__genmod
          INTERFACE 
            SUBROUTINE BM_INIT_BLOCK_R2(BM)
              USE SLAU_BLOCK
              TYPE (MAIN_BLOCK_MATRIX) ,TARGET :: BM
            END SUBROUTINE BM_INIT_BLOCK_R2
          END INTERFACE 
        END MODULE BM_INIT_BLOCK_R2__genmod
