        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:06 2024
        MODULE BM_ILU_SOLVE__genmod
          INTERFACE 
            SUBROUTINE BM_ILU_SOLVE(BM,BMILU,X)
              USE SLAU_BLOCK
              TYPE (MAIN_BLOCK_MATRIX) ,TARGET :: BM
              TYPE (MAIN_BLOCK_MATRIX) ,TARGET :: BMILU
              REAL(KIND=8) :: X(:)
            END SUBROUTINE BM_ILU_SOLVE
          END INTERFACE 
        END MODULE BM_ILU_SOLVE__genmod
