        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:05 2024
        MODULE BM_NULL_MROW__genmod
          INTERFACE 
            SUBROUTINE BM_NULL_MROW(MROW)
              USE SLAU_BLOCK
              TYPE (SPARSE_MATRIX_ROW) :: MROW
            END SUBROUTINE BM_NULL_MROW
          END INTERFACE 
        END MODULE BM_NULL_MROW__genmod
