        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 13 11:10:58 2025
        MODULE BUILD_CURVE__genmod
          INTERFACE 
            SUBROUTINE BUILD_CURVE
            END SUBROUTINE BUILD_CURVE
          END INTERFACE 
        END MODULE BUILD_CURVE__genmod
