        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 13 11:10:58 2025
        MODULE BUILD_BOUND__genmod
          INTERFACE 
            SUBROUTINE BUILD_BOUND
            END SUBROUTINE BUILD_BOUND
          END INTERFACE 
        END MODULE BUILD_BOUND__genmod
