        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:09 2024
        MODULE CALC_SLAU_PARDISO__genmod
          INTERFACE 
            SUBROUTINE CALC_SLAU_PARDISO(VALUES,COLUMNS,ROWINDEX,RHS,   &
     &NROWS,NCOLS,NNONZEROS,SOLUTION,PARDISO_EPS)
              INTEGER(KIND=4) :: NNONZEROS
              INTEGER(KIND=4) :: NCOLS
              INTEGER(KIND=4) :: NROWS
              REAL(KIND=8) :: VALUES(NNONZEROS)
              INTEGER(KIND=4) :: COLUMNS(NNONZEROS)
              INTEGER(KIND=4) :: ROWINDEX(NROWS+1)
              REAL(KIND=8) :: RHS(NROWS)
              REAL(KIND=8) :: SOLUTION(NCOLS)
              INTEGER(KIND=4) :: PARDISO_EPS
            END SUBROUTINE CALC_SLAU_PARDISO
          END INTERFACE 
        END MODULE CALC_SLAU_PARDISO__genmod
