        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 13 11:10:58 2025
        MODULE COORDINATE_FIRST_PARTICLE__genmod
          INTERFACE 
            SUBROUTINE COORDINATE_FIRST_PARTICLE(N,Y,ARR_BOUND,NUM,DLT, &
     &SIZE_ARR)
              INTEGER(KIND=4) :: NUM
              INTEGER(KIND=4) :: N
              REAL(KIND=8) :: Y(N)
              REAL(KIND=8) :: ARR_BOUND(NUM,2)
              REAL(KIND=8) :: DLT
              INTEGER(KIND=4) :: SIZE_ARR
            END SUBROUTINE COORDINATE_FIRST_PARTICLE
          END INTERFACE 
        END MODULE COORDINATE_FIRST_PARTICLE__genmod
