        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:21 2024
        MODULE CP_CALCINT_NF1__genmod
          INTERFACE 
            FUNCTION CP_CALCINT_NF1(MODE)
              INTEGER(KIND=4) :: MODE
              REAL(KIND=8) :: CP_CALCINT_NF1
            END FUNCTION CP_CALCINT_NF1
          END INTERFACE 
        END MODULE CP_CALCINT_NF1__genmod
