        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE DEALLOCATE_GU_GEN__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_GU_GEN(GUG)
              USE PGMOD
              TYPE (TBOUNGLINE_GU_GEN) :: GUG
            END SUBROUTINE DEALLOCATE_GU_GEN
          END INTERFACE 
        END MODULE DEALLOCATE_GU_GEN__genmod
