        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:17 2024
        MODULE DEALLOCATE_BOUNDS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUNDS(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_BOUNDS
          END INTERFACE 
        END MODULE DEALLOCATE_BOUNDS__genmod
