        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE DEALLOCATE_CASHINTEGRALS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_CASHINTEGRALS(C)
              USE PGMOD
              TYPE (TCASHINTEGRAL) :: C
            END SUBROUTINE DEALLOCATE_CASHINTEGRALS
          END INTERFACE 
        END MODULE DEALLOCATE_CASHINTEGRALS__genmod
