        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 13 10:54:11 2025
        MODULE DRAW_SQUARE__genmod
          INTERFACE 
            SUBROUTINE DRAW_SQUARE
            END SUBROUTINE DRAW_SQUARE
          END INTERFACE 
        END MODULE DRAW_SQUARE__genmod
