        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 13 11:10:58 2025
        MODULE DRAW_CURVES__genmod
          INTERFACE 
            SUBROUTINE DRAW_CURVES
            END SUBROUTINE DRAW_CURVES
          END INTERFACE 
        END MODULE DRAW_CURVES__genmod
