        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE FREE_OMP_BUFFER__genmod
          INTERFACE 
            SUBROUTINE FREE_OMP_BUFFER
            END SUBROUTINE FREE_OMP_BUFFER
          END INTERFACE 
        END MODULE FREE_OMP_BUFFER__genmod
