        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:36:14 2024
        MODULE GA_DRW_TRMESH_FUNC_START__genmod
          INTERFACE 
            SUBROUTINE GA_DRW_TRMESH_FUNC_START(IFILE,FILENAME,VARS)
              INTEGER(KIND=4) :: IFILE
              CHARACTER(*) :: FILENAME
              CHARACTER(*) :: VARS
            END SUBROUTINE GA_DRW_TRMESH_FUNC_START
          END INTERFACE 
        END MODULE GA_DRW_TRMESH_FUNC_START__genmod
