        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:36:15 2024
        MODULE GA_DRW_TRMESH__genmod
          INTERFACE 
            SUBROUTINE GA_DRW_TRMESH(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE GA_DRW_TRMESH
          END INTERFACE 
        END MODULE GA_DRW_TRMESH__genmod
