        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:36:15 2024
        MODULE GA_INIT_GEOM_CYLIDER_PARTICLE__genmod
          INTERFACE 
            SUBROUTINE GA_INIT_GEOM_CYLIDER_PARTICLE(X0,Y0,R0,TYPE_GA)
              REAL(KIND=8) :: X0
              REAL(KIND=8) :: Y0
              REAL(KIND=8) :: R0
              INTEGER(KIND=4) :: TYPE_GA
            END SUBROUTINE GA_INIT_GEOM_CYLIDER_PARTICLE
          END INTERFACE 
        END MODULE GA_INIT_GEOM_CYLIDER_PARTICLE__genmod
