        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:36:15 2024
        MODULE GA_INIT_GEOM_ELLIPCE_SYMMETR__genmod
          INTERFACE 
            SUBROUTINE GA_INIT_GEOM_ELLIPCE_SYMMETR(X0,Y0,RX,RY,G0,     &
     &INVERT_OBHOD,NJ)
              REAL(KIND=8) :: X0
              REAL(KIND=8) :: Y0
              REAL(KIND=8) :: RX
              REAL(KIND=8) :: RY
              REAL(KIND=8) :: G0
              LOGICAL(KIND=4) :: INVERT_OBHOD
              INTEGER(KIND=4) :: NJ
            END SUBROUTINE GA_INIT_GEOM_ELLIPCE_SYMMETR
          END INTERFACE 
        END MODULE GA_INIT_GEOM_ELLIPCE_SYMMETR__genmod
