        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:36:15 2024
        MODULE GA_INIT_GEOM_SQUARE_SYMMETR__genmod
          INTERFACE 
            SUBROUTINE GA_INIT_GEOM_SQUARE_SYMMETR(X0,Y0,MCELLNJ,A)
              REAL(KIND=8) :: X0
              REAL(KIND=8) :: Y0
              INTEGER(KIND=4) :: MCELLNJ
              REAL(KIND=8) :: A
            END SUBROUTINE GA_INIT_GEOM_SQUARE_SYMMETR
          END INTERFACE 
        END MODULE GA_INIT_GEOM_SQUARE_SYMMETR__genmod
