        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:35 2024
        MODULE GEOM_COLLOCATE_POINTS_AREA__genmod
          INTERFACE 
            SUBROUTINE GEOM_COLLOCATE_POINTS_AREA
            END SUBROUTINE GEOM_COLLOCATE_POINTS_AREA
          END INTERFACE 
        END MODULE GEOM_COLLOCATE_POINTS_AREA__genmod
