        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:36 2024
        MODULE GEOM_DETALE_POSTPROCESSOR__genmod
          INTERFACE 
            SUBROUTINE GEOM_DETALE_POSTPROCESSOR(IB)
              INTEGER(KIND=4) :: IB
            END SUBROUTINE GEOM_DETALE_POSTPROCESSOR
          END INTERFACE 
        END MODULE GEOM_DETALE_POSTPROCESSOR__genmod
