        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE GET_AA_CASH_INTEGRAL___genmod
          INTERFACE 
            FUNCTION GET_AA_CASH_INTEGRAL_(IA,J,I,NF)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: NF
              REAL(KIND=8) :: GET_AA_CASH_INTEGRAL_
            END FUNCTION GET_AA_CASH_INTEGRAL_
          END INTERFACE 
        END MODULE GET_AA_CASH_INTEGRAL___genmod
