        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE GS_PRINT_STOP__genmod
          INTERFACE 
            SUBROUTINE GS_PRINT_STOP(S)
              CHARACTER(*) :: S
            END SUBROUTINE GS_PRINT_STOP
          END INTERFACE 
        END MODULE GS_PRINT_STOP__genmod
