        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE GS_PRINTINIT_CASH__genmod
          INTERFACE 
            SUBROUTINE GS_PRINTINIT_CASH
            END SUBROUTINE GS_PRINTINIT_CASH
          END INTERFACE 
        END MODULE GS_PRINTINIT_CASH__genmod
