        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:39 2024
        MODULE INIT_BOUNDLINE_GU_SYMMETR__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDLINE_GU_SYMMETR(GU,BNDF,IS_DIRECT,IA,  &
     &IBND,IBNDL,C0_,C1_)
              USE PGMOD
              TYPE (TBOUNDLINE_GU) :: GU
              INTEGER(KIND=4) :: BNDF
              LOGICAL(KIND=4) :: IS_DIRECT
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
              INTEGER(KIND=4) :: IBNDL
              REAL(KIND=8) :: C0_
              REAL(KIND=8) :: C1_
            END SUBROUTINE INIT_BOUNDLINE_GU_SYMMETR
          END INTERFACE 
        END MODULE INIT_BOUNDLINE_GU_SYMMETR__genmod
