        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:39 2024
        MODULE INIT_BOUNDLINE_GU_GENGLOBAL__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDLINE_GU_GENGLOBAL(GU,BNDF,N)
              USE PGMOD
              TYPE (TBOUNDLINE_GU) :: GU
              INTEGER(KIND=4) :: BNDF
              INTEGER(KIND=4) :: N
            END SUBROUTINE INIT_BOUNDLINE_GU_GENGLOBAL
          END INTERFACE 
        END MODULE INIT_BOUNDLINE_GU_GENGLOBAL__genmod
