        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE INIT_NEED_CASH_EQ1__genmod
          INTERFACE 
            SUBROUTINE INIT_NEED_CASH_EQ1(MODE,DER,NEED_CASH_B,         &
     &NEED_CASH_A)
              INTEGER(KIND=4) :: MODE
              INTEGER(KIND=4) :: DER
              LOGICAL(KIND=4) :: NEED_CASH_B(0:)
              LOGICAL(KIND=4) :: NEED_CASH_A(0:)
            END SUBROUTINE INIT_NEED_CASH_EQ1
          END INTERFACE 
        END MODULE INIT_NEED_CASH_EQ1__genmod
