        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE INIT_NEED_CASH_FOR_FUNC__genmod
          INTERFACE 
            SUBROUTINE INIT_NEED_CASH_FOR_FUNC(MODE,DER,IS_BA,IA,       &
     &CLEAR_NEED_CASH)
              INTEGER(KIND=4) :: MODE
              INTEGER(KIND=4) :: DER
              INTEGER(KIND=4) :: IS_BA
              INTEGER(KIND=4) :: IA
              LOGICAL(KIND=4) :: CLEAR_NEED_CASH
            END SUBROUTINE INIT_NEED_CASH_FOR_FUNC
          END INTERFACE 
        END MODULE INIT_NEED_CASH_FOR_FUNC__genmod
