        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:33 2024
        MODULE INIT_GS_TIME__genmod
          INTERFACE 
            SUBROUTINE INIT_GS_TIME
            END SUBROUTINE INIT_GS_TIME
          END INTERFACE 
        END MODULE INIT_GS_TIME__genmod
