        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE INIT_MESH_GU__genmod
          INTERFACE 
            SUBROUTINE INIT_MESH_GU
            END SUBROUTINE INIT_MESH_GU
          END INTERFACE 
        END MODULE INIT_MESH_GU__genmod
