        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:14 2024
        MODULE INITCONST_GREENSOLVE__genmod
          INTERFACE 
            SUBROUTINE INITCONST_GREENSOLVE
            END SUBROUTINE INITCONST_GREENSOLVE
          END INTERFACE 
        END MODULE INITCONST_GREENSOLVE__genmod
