        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE INIT_MESH_GU2__genmod
          INTERFACE 
            SUBROUTINE INIT_MESH_GU2
            END SUBROUTINE INIT_MESH_GU2
          END INTERFACE 
        END MODULE INIT_MESH_GU2__genmod
