        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE NULL_MATRIX__genmod
          INTERFACE 
            SUBROUTINE NULL_MATRIX
            END SUBROUTINE NULL_MATRIX
          END INTERFACE 
        END MODULE NULL_MATRIX__genmod
