        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE PG_ALLOCATE_BOUNDS__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_BOUNDS(INB)
              INTEGER(KIND=4) :: INB
            END SUBROUTINE PG_ALLOCATE_BOUNDS
          END INTERFACE 
        END MODULE PG_ALLOCATE_BOUNDS__genmod
