        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE PG_ALLOCATE_AREAPART_GEOM__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AREAPART_GEOM(IN,INTR,INPE)
              INTEGER(KIND=4) :: IN
              INTEGER(KIND=4) :: INTR
              INTEGER(KIND=4) :: INPE
            END SUBROUTINE PG_ALLOCATE_AREAPART_GEOM
          END INTERFACE 
        END MODULE PG_ALLOCATE_AREAPART_GEOM__genmod
