        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:41 2024
        MODULE PG_ADD_CLOSING_EQ_TO_AREA__genmod
          INTERFACE 
            SUBROUTINE PG_ADD_CLOSING_EQ_TO_AREA(IA,EQ,B)
              INTEGER(KIND=4) :: IA
              REAL(KIND=8) :: EQ(GS%M%NX)
              REAL(KIND=8) :: B
            END SUBROUTINE PG_ADD_CLOSING_EQ_TO_AREA
          END INTERFACE 
        END MODULE PG_ADD_CLOSING_EQ_TO_AREA__genmod
