        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE PG_ALLOCATE_BOUND_GU__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_BOUND_GU
            END SUBROUTINE PG_ALLOCATE_BOUND_GU
          END INTERFACE 
        END MODULE PG_ALLOCATE_BOUND_GU__genmod
