        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE PG_ALLOCATE_DOMAINS__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_DOMAINS(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_ALLOCATE_DOMAINS
          END INTERFACE 
        END MODULE PG_ALLOCATE_DOMAINS__genmod
