        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:14 2024
        MODULE PG_BIND_DOMAIN__genmod
          INTERFACE 
            SUBROUTINE PG_BIND_DOMAIN(K)
              INTEGER(KIND=4) :: K
            END SUBROUTINE PG_BIND_DOMAIN
          END INTERFACE 
        END MODULE PG_BIND_DOMAIN__genmod
