        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:41 2024
        MODULE PG_CLOSING_PSICONST__genmod
          INTERFACE 
            SUBROUTINE PG_CLOSING_PSICONST(IBND)
              INTEGER(KIND=4) :: IBND
            END SUBROUTINE PG_CLOSING_PSICONST
          END INTERFACE 
        END MODULE PG_CLOSING_PSICONST__genmod
