        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:40 2024
        MODULE PG_CLOSING_MATRIX_PERIODIC__genmod
          INTERFACE 
            SUBROUTINE PG_CLOSING_MATRIX_PERIODIC(IBNDL1,IBNDL2,        &
     &IS_DIRECT,DPSI1,DOM)
              INTEGER(KIND=4) :: IBNDL1
              INTEGER(KIND=4) :: IBNDL2
              LOGICAL(KIND=4) :: IS_DIRECT
              REAL(KIND=8) :: DPSI1
              REAL(KIND=8) :: DOM
            END SUBROUTINE PG_CLOSING_MATRIX_PERIODIC
          END INTERFACE 
        END MODULE PG_CLOSING_MATRIX_PERIODIC__genmod
