        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:37 2024
        MODULE PG_COPY_GEOM_DOMAIN_DXDY_ROTATE__genmod
          INTERFACE 
            SUBROUTINE PG_COPY_GEOM_DOMAIN_DXDY_ROTATE(IP,IA,DX,DY,ANGLE&
     &,XR,YR)
              INTEGER(KIND=4) :: IP
              INTEGER(KIND=4) :: IA
              REAL(KIND=8) :: DX
              REAL(KIND=8) :: DY
              REAL(KIND=8) :: ANGLE
              REAL(KIND=8) :: XR
              REAL(KIND=8) :: YR
            END SUBROUTINE PG_COPY_GEOM_DOMAIN_DXDY_ROTATE
          END INTERFACE 
        END MODULE PG_COPY_GEOM_DOMAIN_DXDY_ROTATE__genmod
