        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:41 2024
        MODULE PG_CLOSING_PSICONST_ARR__genmod
          INTERFACE 
            SUBROUTINE PG_CLOSING_PSICONST_ARR(IBND,IBNDL,N)
              INTEGER(KIND=4) :: N
              INTEGER(KIND=4) :: IBND(N)
              INTEGER(KIND=4) :: IBNDL(N)
            END SUBROUTINE PG_CLOSING_PSICONST_ARR
          END INTERFACE 
        END MODULE PG_CLOSING_PSICONST_ARR__genmod
