        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:17 2024
        MODULE PG_DEALLOCATE_MEM__genmod
          INTERFACE 
            SUBROUTINE PG_DEALLOCATE_MEM
            END SUBROUTINE PG_DEALLOCATE_MEM
          END INTERFACE 
        END MODULE PG_DEALLOCATE_MEM__genmod
