        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE PG_DEALLOCATE_GA_BASE__genmod
          INTERFACE 
            SUBROUTINE PG_DEALLOCATE_GA_BASE(GA)
              USE PGMOD
              TYPE (TBOUNLINEFUNCAPPROX) :: GA
            END SUBROUTINE PG_DEALLOCATE_GA_BASE
          END INTERFACE 
        END MODULE PG_DEALLOCATE_GA_BASE__genmod
