        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:44 2024
        MODULE PG_GET_PSIOML__genmod
          INTERFACE 
            SUBROUTINE PG_GET_PSIOML
            END SUBROUTINE PG_GET_PSIOML
          END INTERFACE 
        END MODULE PG_GET_PSIOML__genmod
