        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:39 2024
        MODULE PG_INIT_BOUNDLINE_GU_GENGLOBAL_CONST__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_GENGLOBAL_CONST(IGU,I,IND,  &
     &VARCONST)
              INTEGER(KIND=4) :: IGU
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: IND
              REAL(KIND=8) :: VARCONST
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_GENGLOBAL_CONST
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_GENGLOBAL_CONST__genmod
