        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:17 2024
        MODULE PG_INIT_AREA_GU_OSS__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_AREA_GU_OSS
            END SUBROUTINE PG_INIT_AREA_GU_OSS
          END INTERFACE 
        END MODULE PG_INIT_AREA_GU_OSS__genmod
