        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:39 2024
        MODULE PG_INIT_BOUNDLINE_GU_GENGLOBAL__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_GENGLOBAL(IGU,BNDF,N)
              INTEGER(KIND=4) :: IGU
              INTEGER(KIND=4) :: BNDF
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_GENGLOBAL
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_GENGLOBAL__genmod
