        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:14 2024
        MODULE PG_STOP_WRITE_LOG_FILE__genmod
          INTERFACE 
            SUBROUTINE PG_STOP_WRITE_LOG_FILE
            END SUBROUTINE PG_STOP_WRITE_LOG_FILE
          END INTERFACE 
        END MODULE PG_STOP_WRITE_LOG_FILE__genmod
