        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:33 2024
        MODULE PREPARE_GLOBAL_SPARSEM__genmod
          INTERFACE 
            SUBROUTINE PREPARE_GLOBAL_SPARSEM
            END SUBROUTINE PREPARE_GLOBAL_SPARSEM
          END INTERFACE 
        END MODULE PREPARE_GLOBAL_SPARSEM__genmod
