        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:33 2024
        MODULE PRINT_TOTAL_TIME__genmod
          INTERFACE 
            SUBROUTINE PRINT_TOTAL_TIME
            END SUBROUTINE PRINT_TOTAL_TIME
          END INTERFACE 
        END MODULE PRINT_TOTAL_TIME__genmod
