        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE REALLOCATE_MM__genmod
          INTERFACE 
            SUBROUTINE REALLOCATE_MM(NU,NX)
              INTEGER(KIND=4) :: NU
              INTEGER(KIND=4) :: NX
            END SUBROUTINE REALLOCATE_MM
          END INTERFACE 
        END MODULE REALLOCATE_MM__genmod
