        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 13 11:10:58 2025
        MODULE SEARCH_FOR_EXTREME_PARTICLES__genmod
          INTERFACE 
            FUNCTION SEARCH_FOR_EXTREME_PARTICLES
              REAL(KIND=8) :: SEARCH_FOR_EXTREME_PARTICLES
            END FUNCTION SEARCH_FOR_EXTREME_PARTICLES
          END INTERFACE 
        END MODULE SEARCH_FOR_EXTREME_PARTICLES__genmod
