        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:17 2024
        MODULE SET_DOMAIN_EQUATION__genmod
          INTERFACE 
            SUBROUTINE SET_DOMAIN_EQUATION(TYPE_EQ,TYPE_EQ2)
              INTEGER(KIND=4) :: TYPE_EQ
              INTEGER(KIND=4) :: TYPE_EQ2
            END SUBROUTINE SET_DOMAIN_EQUATION
          END INTERFACE 
        END MODULE SET_DOMAIN_EQUATION__genmod
