        !COMPILER-GENERATED INTERFACE MODULE: Mon Jan 13 11:10:58 2025
        MODULE SOLVE__genmod
          INTERFACE 
            SUBROUTINE SOLVE
            END SUBROUTINE SOLVE
          END INTERFACE 
        END MODULE SOLVE__genmod
