        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE SPARSE_TO_M__genmod
          INTERFACE 
            SUBROUTINE SPARSE_TO_M
            END SUBROUTINE SPARSE_TO_M
          END INTERFACE 
        END MODULE SPARSE_TO_M__genmod
