        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:21 2024
        MODULE TEST_CP_CINT__genmod
          INTERFACE 
            SUBROUTINE TEST_CP_CINT
            END SUBROUTINE TEST_CP_CINT
          END INTERFACE 
        END MODULE TEST_CP_CINT__genmod
