        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE TEST_M_DIAGONAL__genmod
          INTERFACE 
            SUBROUTINE TEST_M_DIAGONAL
            END SUBROUTINE TEST_M_DIAGONAL
          END INTERFACE 
        END MODULE TEST_M_DIAGONAL__genmod
