        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:36:15 2024
        MODULE TEST_BOUNDLINES_CIRCLE__genmod
          INTERFACE 
            FUNCTION TEST_BOUNDLINES_CIRCLE(IB,IBL1,IBL2,DGAM) RESULT(  &
     &IS_CIRC)
              INTEGER(KIND=4) :: IB
              INTEGER(KIND=4) :: IBL1
              INTEGER(KIND=4) :: IBL2
              REAL(KIND=8) :: DGAM
              LOGICAL(KIND=4) :: IS_CIRC
            END FUNCTION TEST_BOUNDLINES_CIRCLE
          END INTERFACE 
        END MODULE TEST_BOUNDLINES_CIRCLE__genmod
