        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE WRITE_MATRIX_MM__genmod
          INTERFACE 
            SUBROUTINE WRITE_MATRIX_MM
            END SUBROUTINE WRITE_MATRIX_MM
          END INTERFACE 
        END MODULE WRITE_MATRIX_MM__genmod
