        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:03 2024
        MODULE ADD_EQUATION_TO_MATRIX_THREAD__genmod
          INTERFACE 
            SUBROUTINE ADD_EQUATION_TO_MATRIX_THREAD(ITH,IA)
              INTEGER(KIND=4) :: ITH
              INTEGER(KIND=4) :: IA
            END SUBROUTINE ADD_EQUATION_TO_MATRIX_THREAD
          END INTERFACE 
        END MODULE ADD_EQUATION_TO_MATRIX_THREAD__genmod
