        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE ALLOCATE_AREA_COLLOCATE_POINTS__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_AREA_COLLOCATE_POINTS(IA,INCP)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: INCP
            END SUBROUTINE ALLOCATE_AREA_COLLOCATE_POINTS
          END INTERFACE 
        END MODULE ALLOCATE_AREA_COLLOCATE_POINTS__genmod
