        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE ALLOCATE_BOUNDLINE_GEOM2__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_BOUNDLINE_GEOM2(IBNDL)
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE ALLOCATE_BOUNDLINE_GEOM2
          END INTERFACE 
        END MODULE ALLOCATE_BOUNDLINE_GEOM2__genmod
