        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE ALLOCATE_GEOM_DETALE_FOR_NEXT__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_GEOM_DETALE_FOR_NEXT
            END SUBROUTINE ALLOCATE_GEOM_DETALE_FOR_NEXT
          END INTERFACE 
        END MODULE ALLOCATE_GEOM_DETALE_FOR_NEXT__genmod
