        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE ALLOCATE_GU_USE__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_GU_USE
            END SUBROUTINE ALLOCATE_GU_USE
          END INTERFACE 
        END MODULE ALLOCATE_GU_USE__genmod
