        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE BLOCK_DIAGONAL_TO_M__genmod
          INTERFACE 
            SUBROUTINE BLOCK_DIAGONAL_TO_M
            END SUBROUTINE BLOCK_DIAGONAL_TO_M
          END INTERFACE 
        END MODULE BLOCK_DIAGONAL_TO_M__genmod
