        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 15:15:02 2024
        MODULE BM_BICGSTAB_TEST2__genmod
          INTERFACE 
            SUBROUTINE BM_BICGSTAB_TEST2
            END SUBROUTINE BM_BICGSTAB_TEST2
          END INTERFACE 
        END MODULE BM_BICGSTAB_TEST2__genmod
