        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 15:15:02 2024
        MODULE BM_DEALLOCATE_BLOCK__genmod
          INTERFACE 
            SUBROUTINE BM_DEALLOCATE_BLOCK(B)
              USE SLAU_BLOCK
              TYPE (BLOCK_MATRIX) :: B
            END SUBROUTINE BM_DEALLOCATE_BLOCK
          END INTERFACE 
        END MODULE BM_DEALLOCATE_BLOCK__genmod
