        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 15:15:01 2024
        MODULE BM_DEALLOCATE_SPARSE_M__genmod
          INTERFACE 
            SUBROUTINE BM_DEALLOCATE_SPARSE_M(SPARSE)
              USE SLAU_BLOCK
              TYPE (SPARSE_MATRIX) :: SPARSE
            END SUBROUTINE BM_DEALLOCATE_SPARSE_M
          END INTERFACE 
        END MODULE BM_DEALLOCATE_SPARSE_M__genmod
