        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 15:15:02 2024
        MODULE BM_ILU_TEST__genmod
          INTERFACE 
            SUBROUTINE BM_ILU_TEST
            END SUBROUTINE BM_ILU_TEST
          END INTERFACE 
        END MODULE BM_ILU_TEST__genmod
