        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:07 2024
        MODULE CALCINT_NF45Z__genmod
          INTERFACE 
            FUNCTION CALCINT_NF45Z(Z0,Z1,Z2)
              COMPLEX(KIND=8) :: Z0
              COMPLEX(KIND=8) :: Z1
              COMPLEX(KIND=8) :: Z2
              COMPLEX(KIND=8) :: CALCINT_NF45Z
            END FUNCTION CALCINT_NF45Z
          END INTERFACE 
        END MODULE CALCINT_NF45Z__genmod
