        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 15:15:14 2024
        MODULE COLLENEAR3Z__genmod
          INTERFACE 
            FUNCTION COLLENEAR3Z(Z1,Z2,Z3)
              COMPLEX(KIND=8) :: Z1
              COMPLEX(KIND=8) :: Z2
              COMPLEX(KIND=8) :: Z3
              LOGICAL(KIND=4) :: COLLENEAR3Z
            END FUNCTION COLLENEAR3Z
          END INTERFACE 
        END MODULE COLLENEAR3Z__genmod
