        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:19 2024
        MODULE CP_CALCINT_NF2425___genmod
          INTERFACE 
            FUNCTION CP_CALCINT_NF2425_(ZTC,R,MODE,NF) RESULT(          &
     &CP_CALCINT_NF2425)
              COMPLEX(KIND=8) :: ZTC
              REAL(KIND=8) :: R
              INTEGER(KIND=4) :: MODE
              INTEGER(KIND=4) :: NF
              REAL(KIND=8) :: CP_CALCINT_NF2425
            END FUNCTION CP_CALCINT_NF2425_
          END INTERFACE 
        END MODULE CP_CALCINT_NF2425___genmod
