        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:18 2024
        MODULE CP_CALCINT_NF2627Z__genmod
          INTERFACE 
            FUNCTION CP_CALCINT_NF2627Z(ZTC,R,MODE)
              COMPLEX(KIND=8) :: ZTC
              REAL(KIND=8) :: R
              INTEGER(KIND=4) :: MODE
              COMPLEX(KIND=8) :: CP_CALCINT_NF2627Z
            END FUNCTION CP_CALCINT_NF2627Z
          END INTERFACE 
        END MODULE CP_CALCINT_NF2627Z__genmod
