        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE DEALLOCATE_COL_INFO__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_COL_INFO(CI)
              USE PGMOD
              TYPE (COL_INFO) :: CI
            END SUBROUTINE DEALLOCATE_COL_INFO
          END INTERFACE 
        END MODULE DEALLOCATE_COL_INFO__genmod
