        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:58 2024
        MODULE DEALLOCATE_BOUNDS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUNDS(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_BOUNDS
          END INTERFACE 
        END MODULE DEALLOCATE_BOUNDS__genmod
