        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:58 2024
        MODULE DEALLOCATE_DOMAINS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_DOMAINS
            END SUBROUTINE DEALLOCATE_DOMAINS
          END INTERFACE 
        END MODULE DEALLOCATE_DOMAINS__genmod
