        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE DEALLOCATE_BOUNDLINE2_GA__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUNDLINE2_GA(IA,IBND,IBNDL)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE DEALLOCATE_BOUNDLINE2_GA
          END INTERFACE 
        END MODULE DEALLOCATE_BOUNDLINE2_GA__genmod
