        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE DEALLOCATE_BOUND_COLLOCATE_POINTS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUND_COLLOCATE_POINTS(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_BOUND_COLLOCATE_POINTS
          END INTERFACE 
        END MODULE DEALLOCATE_BOUND_COLLOCATE_POINTS__genmod
