        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE DEALLOCATE_BOUNDLINE_GU__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUNDLINE_GU(IA,IBND,IBNDL)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE DEALLOCATE_BOUNDLINE_GU
          END INTERFACE 
        END MODULE DEALLOCATE_BOUNDLINE_GU__genmod
