        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:58 2024
        MODULE DEALLOCATE_BOUNDLINES__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUNDLINES(IA,IBND)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
            END SUBROUTINE DEALLOCATE_BOUNDLINES
          END INTERFACE 
        END MODULE DEALLOCATE_BOUNDLINES__genmod
