        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE DEALLOCATE_GU_GEN__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_GU_GEN(GUG)
              USE PGMOD
              TYPE (TBOUNGLINE_GU_GEN) :: GUG
            END SUBROUTINE DEALLOCATE_GU_GEN
          END INTERFACE 
        END MODULE DEALLOCATE_GU_GEN__genmod
