        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE DEALLOCATE_CASH__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_CASH(CASH)
              USE PGMOD
              TYPE (TCASH) :: CASH
            END SUBROUTINE DEALLOCATE_CASH
          END INTERFACE 
        END MODULE DEALLOCATE_CASH__genmod
