        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE DEALLOCATE_CASHINTEGRALS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_CASHINTEGRALS(C)
              USE PGMOD
              TYPE (TCASHINTEGRAL) :: C
            END SUBROUTINE DEALLOCATE_CASHINTEGRALS
          END INTERFACE 
        END MODULE DEALLOCATE_CASHINTEGRALS__genmod
