        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE DRW_MATRIX__genmod
          INTERFACE 
            SUBROUTINE DRW_MATRIX
            END SUBROUTINE DRW_MATRIX
          END INTERFACE 
        END MODULE DRW_MATRIX__genmod
