        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:03 2024
        MODULE END_WRITE_BY_TIME__genmod
          INTERFACE 
            SUBROUTINE END_WRITE_BY_TIME
            END SUBROUTINE END_WRITE_BY_TIME
          END INTERFACE 
        END MODULE END_WRITE_BY_TIME__genmod
