        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE FREE_OMP_BUFFER__genmod
          INTERFACE 
            SUBROUTINE FREE_OMP_BUFFER
            END SUBROUTINE FREE_OMP_BUFFER
          END INTERFACE 
        END MODULE FREE_OMP_BUFFER__genmod
