        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:21 2024
        MODULE GA_DRW_TRMESH_WRITE_POINT__genmod
          INTERFACE 
            SUBROUTINE GA_DRW_TRMESH_WRITE_POINT(IFILE,I)
              INTEGER(KIND=4) :: IFILE
              INTEGER(KIND=4) :: I
            END SUBROUTINE GA_DRW_TRMESH_WRITE_POINT
          END INTERFACE 
        END MODULE GA_DRW_TRMESH_WRITE_POINT__genmod
