        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:22 2024
        MODULE GA_DRW_TRMESH_FUNC__genmod
          INTERFACE 
            SUBROUTINE GA_DRW_TRMESH_FUNC(FILENAME,VARS,WRITE_POINT)
              CHARACTER(*) :: FILENAME
              CHARACTER(*) :: VARS
              EXTERNAL WRITE_POINT
            END SUBROUTINE GA_DRW_TRMESH_FUNC
          END INTERFACE 
        END MODULE GA_DRW_TRMESH_FUNC__genmod
