        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:22 2024
        MODULE GA_DRW_TRMESH__genmod
          INTERFACE 
            SUBROUTINE GA_DRW_TRMESH(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE GA_DRW_TRMESH
          END INTERFACE 
        END MODULE GA_DRW_TRMESH__genmod
