        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:22 2024
        MODULE GA_DRW_TRMESH_FUNC_ZONE__genmod
          INTERFACE 
            SUBROUTINE GA_DRW_TRMESH_FUNC_ZONE(IFILE,ZONENAME,          &
     &WRITE_POINT)
              INTEGER(KIND=4) :: IFILE
              CHARACTER(*) :: ZONENAME
              EXTERNAL WRITE_POINT
            END SUBROUTINE GA_DRW_TRMESH_FUNC_ZONE
          END INTERFACE 
        END MODULE GA_DRW_TRMESH_FUNC_ZONE__genmod
