        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:21 2024
        MODULE GA_GET_OM_PARTICLE__genmod
          INTERFACE 
            FUNCTION GA_GET_OM_PARTICLE(IB) RESULT(OM1)
              INTEGER(KIND=4) :: IB
              REAL(KIND=8) :: OM1
            END FUNCTION GA_GET_OM_PARTICLE
          END INTERFACE 
        END MODULE GA_GET_OM_PARTICLE__genmod
