        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:22 2024
        MODULE GA_GRADP_BOUNDLINE__genmod
          INTERFACE 
            FUNCTION GA_GRADP_BOUNDLINE(IB,IBL) RESULT(F)
              INTEGER(KIND=4) :: IB
              INTEGER(KIND=4) :: IBL
              REAL(KIND=8) :: F
            END FUNCTION GA_GRADP_BOUNDLINE
          END INTERFACE 
        END MODULE GA_GRADP_BOUNDLINE__genmod
