        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:21 2024
        MODULE GA_INIT_MESH_RCELL_QUADS__genmod
          INTERFACE 
            SUBROUTINE GA_INIT_MESH_RCELL_QUADS(RR,GG,NR1,NG1)
              INTEGER(KIND=4) :: NG1
              INTEGER(KIND=4) :: NR1
              REAL(KIND=8) :: RR(NR1)
              REAL(KIND=8) :: GG(NG1)
            END SUBROUTINE GA_INIT_MESH_RCELL_QUADS
          END INTERFACE 
        END MODULE GA_INIT_MESH_RCELL_QUADS__genmod
