        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:21 2024
        MODULE GA_INIT_GEOM_CIRCLE__genmod
          INTERFACE 
            SUBROUTINE GA_INIT_GEOM_CIRCLE(X0,Y0,R0,INVERT_OBHOD,NJ)
              REAL(KIND=8) :: X0
              REAL(KIND=8) :: Y0
              REAL(KIND=8) :: R0
              LOGICAL(KIND=4) :: INVERT_OBHOD
              INTEGER(KIND=4) :: NJ
            END SUBROUTINE GA_INIT_GEOM_CIRCLE
          END INTERFACE 
        END MODULE GA_INIT_GEOM_CIRCLE__genmod
