        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:22 2024
        MODULE GA_INTF_ONELINE_BASE__genmod
          INTERFACE 
            FUNCTION GA_INTF_ONELINE_BASE(IFS,NF)
              USE PGMOD
              TYPE (INTF_STRUCT) :: IFS
              INTEGER(KIND=4) :: NF
              REAL(KIND=8) :: GA_INTF_ONELINE_BASE
            END FUNCTION GA_INTF_ONELINE_BASE
          END INTERFACE 
        END MODULE GA_INTF_ONELINE_BASE__genmod
