        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:22 2024
        MODULE GA_READMESHMSH__genmod
          INTERFACE 
            SUBROUTINE GA_READMESHMSH(FNAME)
              CHARACTER(*) :: FNAME
            END SUBROUTINE GA_READMESHMSH
          END INTERFACE 
        END MODULE GA_READMESHMSH__genmod
