        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:22 2024
        MODULE GA_READMESHVTK__genmod
          INTERFACE 
            SUBROUTINE GA_READMESHVTK(FNAME)
              CHARACTER(*) :: FNAME
            END SUBROUTINE GA_READMESHVTK
          END INTERFACE 
        END MODULE GA_READMESHVTK__genmod
