        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:16 2024
        MODULE GEOM_COLLOCATE_POINTS_AREA__genmod
          INTERFACE 
            SUBROUTINE GEOM_COLLOCATE_POINTS_AREA
            END SUBROUTINE GEOM_COLLOCATE_POINTS_AREA
          END INTERFACE 
        END MODULE GEOM_COLLOCATE_POINTS_AREA__genmod
