        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:16 2024
        MODULE GEOM_DETALE_POSTPROCESSOR__genmod
          INTERFACE 
            SUBROUTINE GEOM_DETALE_POSTPROCESSOR(IB)
              INTEGER(KIND=4) :: IB
            END SUBROUTINE GEOM_DETALE_POSTPROCESSOR
          END INTERFACE 
        END MODULE GEOM_DETALE_POSTPROCESSOR__genmod
