        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE GET_AA_CASH_INTEGRAL__genmod
          INTERFACE 
            FUNCTION GET_AA_CASH_INTEGRAL(IA,J,I,NF)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: NF
              REAL(KIND=8) :: GET_AA_CASH_INTEGRAL
            END FUNCTION GET_AA_CASH_INTEGRAL
          END INTERFACE 
        END MODULE GET_AA_CASH_INTEGRAL__genmod
