        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:12 2024
        MODULE GET_PSIOML__genmod
          INTERFACE 
            SUBROUTINE GET_PSIOML(IA,KND)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: KND
            END SUBROUTINE GET_PSIOML
          END INTERFACE 
        END MODULE GET_PSIOML__genmod
