        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE GET_IND_AREA3__genmod
          INTERFACE 
            SUBROUTINE GET_IND_AREA3
            END SUBROUTINE GET_IND_AREA3
          END INTERFACE 
        END MODULE GET_IND_AREA3__genmod
