        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:04 2024
        MODULE GET_MATRIX_AREA_BP__genmod
          INTERFACE 
            SUBROUTINE GET_MATRIX_AREA_BP(IA,ICP,FUNC_INF)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: ICP
              REAL(KIND=8) :: FUNC_INF
              EXTERNAL FUNC_INF
            END SUBROUTINE GET_MATRIX_AREA_BP
          END INTERFACE 
        END MODULE GET_MATRIX_AREA_BP__genmod
