        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:13 2024
        MODULE GET_ARVAL_FUNP__genmod
          INTERFACE 
            SUBROUTINE GET_ARVAL_FUNP(KU,KND)
              INTEGER(KIND=4) :: KU
              INTEGER(KIND=4) :: KND
            END SUBROUTINE GET_ARVAL_FUNP
          END INTERFACE 
        END MODULE GET_ARVAL_FUNP__genmod
