        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:03 2024
        MODULE GET_IND_AREA2__genmod
          INTERFACE 
            SUBROUTINE GET_IND_AREA2(IA,J)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: J
            END SUBROUTINE GET_IND_AREA2
          END INTERFACE 
        END MODULE GET_IND_AREA2__genmod
