        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE GS_PRINTINIT_CASH__genmod
          INTERFACE 
            SUBROUTINE GS_PRINTINIT_CASH
            END SUBROUTINE GS_PRINTINIT_CASH
          END INTERFACE 
        END MODULE GS_PRINTINIT_CASH__genmod
