        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE INIT_BM_ORDER__genmod
          INTERFACE 
            SUBROUTINE INIT_BM_ORDER
            END SUBROUTINE INIT_BM_ORDER
          END INTERFACE 
        END MODULE INIT_BM_ORDER__genmod
