        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE INIT_NEED_CASH_EQ4__genmod
          INTERFACE 
            SUBROUTINE INIT_NEED_CASH_EQ4(MODE,DER,NEED_CASH_B,         &
     &NEED_CASH_A)
              INTEGER(KIND=4) :: MODE
              INTEGER(KIND=4) :: DER
              LOGICAL(KIND=4) :: NEED_CASH_B(0:)
              LOGICAL(KIND=4) :: NEED_CASH_A(0:)
            END SUBROUTINE INIT_NEED_CASH_EQ4
          END INTERFACE 
        END MODULE INIT_NEED_CASH_EQ4__genmod
