        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:03 2024
        MODULE INITCASH_AREA__genmod
          INTERFACE 
            SUBROUTINE INITCASH_AREA(I)
              INTEGER(KIND=4) :: I
            END SUBROUTINE INITCASH_AREA
          END INTERFACE 
        END MODULE INITCASH_AREA__genmod
