        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE INIT_NEED_CASH_FOR_MATRIX__genmod
          INTERFACE 
            SUBROUTINE INIT_NEED_CASH_FOR_MATRIX(I)
              INTEGER(KIND=4) :: I
            END SUBROUTINE INIT_NEED_CASH_FOR_MATRIX
          END INTERFACE 
        END MODULE INIT_NEED_CASH_FOR_MATRIX__genmod
