        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE INIT_GSMAIN_S_NDNS__genmod
          INTERFACE 
            SUBROUTINE INIT_GSMAIN_S_NDNS(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE INIT_GSMAIN_S_NDNS
          END INTERFACE 
        END MODULE INIT_GSMAIN_S_NDNS__genmod
