        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:16 2024
        MODULE INIT_GEOM_DETALE_BNDL__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM_DETALE_BNDL(IBNDL)
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE INIT_GEOM_DETALE_BNDL
          END INTERFACE 
        END MODULE INIT_GEOM_DETALE_BNDL__genmod
