        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE INIT_MESH_GU__genmod
          INTERFACE 
            SUBROUTINE INIT_MESH_GU
            END SUBROUTINE INIT_MESH_GU
          END INTERFACE 
        END MODULE INIT_MESH_GU__genmod
