        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE INITCASHINTEGRAL__genmod
          INTERFACE 
            SUBROUTINE INITCASHINTEGRAL(C)
              USE PGMOD
              TYPE (TCASHINTEGRAL) :: C
            END SUBROUTINE INITCASHINTEGRAL
          END INTERFACE 
        END MODULE INITCASHINTEGRAL__genmod
