        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:04 2024
        MODULE INITCASH__genmod
          INTERFACE 
            SUBROUTINE INITCASH
            END SUBROUTINE INITCASH
          END INTERFACE 
        END MODULE INITCASH__genmod
