        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:03 2024
        MODULE INIT_GS_TIME__genmod
          INTERFACE 
            SUBROUTINE INIT_GS_TIME
            END SUBROUTINE INIT_GS_TIME
          END INTERFACE 
        END MODULE INIT_GS_TIME__genmod
