        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE INITCONST_GREENSOLVE__genmod
          INTERFACE 
            SUBROUTINE INITCONST_GREENSOLVE
            END SUBROUTINE INITCONST_GREENSOLVE
          END INTERFACE 
        END MODULE INITCONST_GREENSOLVE__genmod
