        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE INIT_AREA_CASH__genmod
          INTERFACE 
            SUBROUTINE INIT_AREA_CASH(CASH)
              USE PGMOD
              TYPE (TCASH) :: CASH
            END SUBROUTINE INIT_AREA_CASH
          END INTERFACE 
        END MODULE INIT_AREA_CASH__genmod
