        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:16 2024
        MODULE INIT_BOUNDLINE_GEOM__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDLINE_GEOM(IBNDL,NPANEL,X,Y,INVERT)
              INTEGER(KIND=4) :: NPANEL
              INTEGER(KIND=4) :: IBNDL
              REAL(KIND=8) :: X(NPANEL+1)
              REAL(KIND=8) :: Y(NPANEL+1)
              LOGICAL(KIND=4) :: INVERT
            END SUBROUTINE INIT_BOUNDLINE_GEOM
          END INTERFACE 
        END MODULE INIT_BOUNDLINE_GEOM__genmod
