        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE INIT_MESH_GU2__genmod
          INTERFACE 
            SUBROUTINE INIT_MESH_GU2
            END SUBROUTINE INIT_MESH_GU2
          END INTERFACE 
        END MODULE INIT_MESH_GU2__genmod
