        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE INIT_OMP_BUFFER__genmod
          INTERFACE 
            SUBROUTINE INIT_OMP_BUFFER
            END SUBROUTINE INIT_OMP_BUFFER
          END INTERFACE 
        END MODULE INIT_OMP_BUFFER__genmod
