        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:16 2024
        MODULE INIT_BOUNDLINE_GEOMLINEDS3_ARRAY_MODE1__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDLINE_GEOMLINEDS3_ARRAY_MODE1(DS1,DS2,KK&
     &,MODE,X1,Y1,X2,Y2,MIN_NP,VX,VY,NPANEL,NPANEL_K)
              USE PGMOD
              REAL(KIND=8) :: DS1
              REAL(KIND=8) :: DS2
              REAL(KIND=8) :: KK
              INTEGER(KIND=4) :: MODE
              REAL(KIND=8) :: X1
              REAL(KIND=8) :: Y1
              REAL(KIND=8) :: X2
              REAL(KIND=8) :: Y2
              INTEGER(KIND=4) :: MIN_NP
              TYPE (TAREAVALUE) ,TARGET :: VX
              TYPE (TAREAVALUE) ,TARGET :: VY
              INTEGER(KIND=4) :: NPANEL
              INTEGER(KIND=4) :: NPANEL_K
            END SUBROUTINE INIT_BOUNDLINE_GEOMLINEDS3_ARRAY_MODE1
          END INTERFACE 
        END MODULE INIT_BOUNDLINE_GEOMLINEDS3_ARRAY_MODE1__genmod
