        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:21 2024
        MODULE INIT_MESH_QUADCELL_TEST__genmod
          INTERFACE 
            SUBROUTINE INIT_MESH_QUADCELL_TEST(XX,YY,NX1,NY1,NPE,FTEST, &
     &HAVE_FTEST)
              INTEGER(KIND=4) :: NY1
              INTEGER(KIND=4) :: NX1
              REAL(KIND=8) :: XX(NX1)
              REAL(KIND=8) :: YY(NY1)
              INTEGER(KIND=4) :: NPE
              LOGICAL(KIND=4) :: FTEST
              EXTERNAL FTEST
              LOGICAL(KIND=4) :: HAVE_FTEST
            END SUBROUTINE INIT_MESH_QUADCELL_TEST
          END INTERFACE 
        END MODULE INIT_MESH_QUADCELL_TEST__genmod
