        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:05 2024
        MODULE INTD_AN45_CORNZ__genmod
          INTERFACE 
            FUNCTION INTD_AN45_CORNZ(Z1,Z2,Z3)
              COMPLEX(KIND=8) :: Z1
              COMPLEX(KIND=8) :: Z2
              COMPLEX(KIND=8) :: Z3
              COMPLEX(KIND=8) :: INTD_AN45_CORNZ
            END FUNCTION INTD_AN45_CORNZ
          END INTERFACE 
        END MODULE INTD_AN45_CORNZ__genmod
