        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE M_TO_SPARSE__genmod
          INTERFACE 
            SUBROUTINE M_TO_SPARSE
            END SUBROUTINE M_TO_SPARSE
          END INTERFACE 
        END MODULE M_TO_SPARSE__genmod
