        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:03 2024
        MODULE MATRIX_RESORT__genmod
          INTERFACE 
            SUBROUTINE MATRIX_RESORT
            END SUBROUTINE MATRIX_RESORT
          END INTERFACE 
        END MODULE MATRIX_RESORT__genmod
