        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE NULL_AREAPART__genmod
          INTERFACE 
            SUBROUTINE NULL_AREAPART(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE NULL_AREAPART
          END INTERFACE 
        END MODULE NULL_AREAPART__genmod
