        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE NULL_MATRIX__genmod
          INTERFACE 
            SUBROUTINE NULL_MATRIX
            END SUBROUTINE NULL_MATRIX
          END INTERFACE 
        END MODULE NULL_MATRIX__genmod
