        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE NULLBOUNDLINE2__genmod
          INTERFACE 
            SUBROUTINE NULLBOUNDLINE2(IBNDL)
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE NULLBOUNDLINE2
          END INTERFACE 
        END MODULE NULLBOUNDLINE2__genmod
