        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE NULLBOUND__genmod
          INTERFACE 
            SUBROUTINE NULLBOUND(IBND)
              INTEGER(KIND=4) :: IBND
            END SUBROUTINE NULLBOUND
          END INTERFACE 
        END MODULE NULLBOUND__genmod
