        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE NULLBOUNDLINE__genmod
          INTERFACE 
            SUBROUTINE NULLBOUNDLINE(IBNDL)
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE NULLBOUNDLINE
          END INTERFACE 
        END MODULE NULLBOUNDLINE__genmod
