        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE PG_ALLOCATE_BOUNDLINE_GU_ADD2__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_BOUNDLINE_GU_ADD2(CP_LINE)
              LOGICAL(KIND=4) :: CP_LINE
            END SUBROUTINE PG_ALLOCATE_BOUNDLINE_GU_ADD2
          END INTERFACE 
        END MODULE PG_ALLOCATE_BOUNDLINE_GU_ADD2__genmod
