        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE PG_ALLOCATE_AREAPART_GEOM_TR__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AREAPART_GEOM_TR(INTR,INPE)
              INTEGER(KIND=4) :: INTR
              INTEGER(KIND=4) :: INPE
            END SUBROUTINE PG_ALLOCATE_AREAPART_GEOM_TR
          END INTERFACE 
        END MODULE PG_ALLOCATE_AREAPART_GEOM_TR__genmod
