        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE PG_ALLOCATE_BOUND_GU2__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_BOUND_GU2
            END SUBROUTINE PG_ALLOCATE_BOUND_GU2
          END INTERFACE 
        END MODULE PG_ALLOCATE_BOUND_GU2__genmod
