        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:16 2024
        MODULE PG_AREAGEOM_POSTPROCESSOR__genmod
          INTERFACE 
            SUBROUTINE PG_AREAGEOM_POSTPROCESSOR
            END SUBROUTINE PG_AREAGEOM_POSTPROCESSOR
          END INTERFACE 
        END MODULE PG_AREAGEOM_POSTPROCESSOR__genmod
