        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE PG_ALLOCATE_CONSTVALIND__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_CONSTVALIND(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_ALLOCATE_CONSTVALIND
          END INTERFACE 
        END MODULE PG_ALLOCATE_CONSTVALIND__genmod
