        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE PG_ALLOCATE_BOUNDS__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_BOUNDS(INB)
              INTEGER(KIND=4) :: INB
            END SUBROUTINE PG_ALLOCATE_BOUNDS
          END INTERFACE 
        END MODULE PG_ALLOCATE_BOUNDS__genmod
