        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE PG_ALLOCATE_AND_SET_GA2__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AND_SET_GA2(IGA,N)
              INTEGER(KIND=4) :: IGA
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_ALLOCATE_AND_SET_GA2
          END INTERFACE 
        END MODULE PG_ALLOCATE_AND_SET_GA2__genmod
