        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE PG_ALLOCATE_AREA__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AREA(INPART)
              INTEGER(KIND=4) :: INPART
            END SUBROUTINE PG_ALLOCATE_AREA
          END INTERFACE 
        END MODULE PG_ALLOCATE_AREA__genmod
