        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE PG_ALLOCATE_AND_SET_GA2_BASE__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AND_SET_GA2_BASE(GA,N)
              USE PGMOD
              TYPE (TBOUNLINEFUNCAPPROX) :: GA
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_ALLOCATE_AND_SET_GA2_BASE
          END INTERFACE 
        END MODULE PG_ALLOCATE_AND_SET_GA2_BASE__genmod
