        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE PG_ALLOCATE_AREAPART_GEOM_N__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AREAPART_GEOM_N(IN)
              INTEGER(KIND=4) :: IN
            END SUBROUTINE PG_ALLOCATE_AREAPART_GEOM_N
          END INTERFACE 
        END MODULE PG_ALLOCATE_AREAPART_GEOM_N__genmod
