        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:57 2024
        MODULE PG_ALLOCATE_AREA_GU__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AREA_GU
            END SUBROUTINE PG_ALLOCATE_AREA_GU
          END INTERFACE 
        END MODULE PG_ALLOCATE_AREA_GU__genmod
