        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE PG_DEALLOCATE_GA_BASE__genmod
          INTERFACE 
            SUBROUTINE PG_DEALLOCATE_GA_BASE(GA)
              USE PGMOD
              TYPE (TBOUNLINEFUNCAPPROX) :: GA
            END SUBROUTINE PG_DEALLOCATE_GA_BASE
          END INTERFACE 
        END MODULE PG_DEALLOCATE_GA_BASE__genmod
