        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:58 2024
        MODULE PG_DEALLOCATE_MEM__genmod
          INTERFACE 
            SUBROUTINE PG_DEALLOCATE_MEM
            END SUBROUTINE PG_DEALLOCATE_MEM
          END INTERFACE 
        END MODULE PG_DEALLOCATE_MEM__genmod
