        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:12 2024
        MODULE PG_GET_PSIOML__genmod
          INTERFACE 
            SUBROUTINE PG_GET_PSIOML
            END SUBROUTINE PG_GET_PSIOML
          END INTERFACE 
        END MODULE PG_GET_PSIOML__genmod
