        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE PG_GET_NEXT_CONSTIND__genmod
          INTERFACE 
            FUNCTION PG_GET_NEXT_CONSTIND
              INTEGER(KIND=4) :: PG_GET_NEXT_CONSTIND
            END FUNCTION PG_GET_NEXT_CONSTIND
          END INTERFACE 
        END MODULE PG_GET_NEXT_CONSTIND__genmod
