        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:04 2024
        MODULE PG_GET_MATRIX__genmod
          INTERFACE 
            SUBROUTINE PG_GET_MATRIX
            END SUBROUTINE PG_GET_MATRIX
          END INTERFACE 
        END MODULE PG_GET_MATRIX__genmod
