        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:58 2024
        MODULE PG_INIT_AREA_GU_CONST__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_AREA_GU_CONST(VAL,K)
              REAL(KIND=8) :: VAL
              INTEGER(KIND=4) :: K
            END SUBROUTINE PG_INIT_AREA_GU_CONST
          END INTERFACE 
        END MODULE PG_INIT_AREA_GU_CONST__genmod
