        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE PG_INIT_AREAPART_GEOM_TR__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_AREAPART_GEOM_TR(TR)
              INTEGER(KIND=4) :: TR(GSAREAPART%NPE*GSAREAPART%NTR)
            END SUBROUTINE PG_INIT_AREAPART_GEOM_TR
          END INTERFACE 
        END MODULE PG_INIT_AREAPART_GEOM_TR__genmod
