        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:58 2024
        MODULE PG_INIT_AREAPART_GU__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_AREAPART_GU(G,K)
              REAL(KIND=8) :: G(GSAREAPART%NTR)
              INTEGER(KIND=4) :: K
            END SUBROUTINE PG_INIT_AREAPART_GU
          END INTERFACE 
        END MODULE PG_INIT_AREAPART_GU__genmod
