        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:04 2024
        MODULE PG_INITCASH_AREA__genmod
          INTERFACE 
            SUBROUTINE PG_INITCASH_AREA
            END SUBROUTINE PG_INITCASH_AREA
          END INTERFACE 
        END MODULE PG_INITCASH_AREA__genmod
