        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:17 2024
        MODULE PG_REBUILD_BOUNDLINE__genmod
          INTERFACE 
            SUBROUTINE PG_REBUILD_BOUNDLINE(IBNDL,N0)
              INTEGER(KIND=4) :: IBNDL
              INTEGER(KIND=4) :: N0
            END SUBROUTINE PG_REBUILD_BOUNDLINE
          END INTERFACE 
        END MODULE PG_REBUILD_BOUNDLINE__genmod
