        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:03 2024
        MODULE PG_SOLVE_BEGIN__genmod
          INTERFACE 
            SUBROUTINE PG_SOLVE_BEGIN
            END SUBROUTINE PG_SOLVE_BEGIN
          END INTERFACE 
        END MODULE PG_SOLVE_BEGIN__genmod
