        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE PG_SET_MATRIX_N_ADD__genmod
          INTERFACE 
            SUBROUTINE PG_SET_MATRIX_N_ADD(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_SET_MATRIX_N_ADD
          END INTERFACE 
        END MODULE PG_SET_MATRIX_N_ADD__genmod
