        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE PG_SET_BOUNDLINE_GU_MODE__genmod
          INTERFACE 
            SUBROUTINE PG_SET_BOUNDLINE_GU_MODE(IBNDL,IMODE)
              INTEGER(KIND=4) :: IBNDL
              INTEGER(KIND=4) :: IMODE
            END SUBROUTINE PG_SET_BOUNDLINE_GU_MODE
          END INTERFACE 
        END MODULE PG_SET_BOUNDLINE_GU_MODE__genmod
