        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:03 2024
        MODULE PG_SOLVE_END__genmod
          INTERFACE 
            SUBROUTINE PG_SOLVE_END(FREE_RES)
              LOGICAL(KIND=4) :: FREE_RES
            END SUBROUTINE PG_SOLVE_END
          END INTERFACE 
        END MODULE PG_SOLVE_END__genmod
