        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:58 2024
        MODULE PG_SET_DOMAIN_EQUATION__genmod
          INTERFACE 
            SUBROUTINE PG_SET_DOMAIN_EQUATION(TYPE_EQ)
              INTEGER(KIND=4) :: TYPE_EQ
            END SUBROUTINE PG_SET_DOMAIN_EQUATION
          END INTERFACE 
        END MODULE PG_SET_DOMAIN_EQUATION__genmod
