        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:55 2024
        MODULE PG_START_WRITE_LOG_FILE__genmod
          INTERFACE 
            SUBROUTINE PG_START_WRITE_LOG_FILE
            END SUBROUTINE PG_START_WRITE_LOG_FILE
          END INTERFACE 
        END MODULE PG_START_WRITE_LOG_FILE__genmod
