        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:58 2024
        MODULE PG_SET_DOMAIN_EQUATION_SYST__genmod
          INTERFACE 
            SUBROUTINE PG_SET_DOMAIN_EQUATION_SYST(TYPE_EQ,TYPE_EQ2)
              INTEGER(KIND=4) :: TYPE_EQ
              INTEGER(KIND=4) :: TYPE_EQ2
            END SUBROUTINE PG_SET_DOMAIN_EQUATION_SYST
          END INTERFACE 
        END MODULE PG_SET_DOMAIN_EQUATION_SYST__genmod
