        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:03 2024
        MODULE PREPARE_GLOBAL_SPARSEM__genmod
          INTERFACE 
            SUBROUTINE PREPARE_GLOBAL_SPARSEM
            END SUBROUTINE PREPARE_GLOBAL_SPARSEM
          END INTERFACE 
        END MODULE PREPARE_GLOBAL_SPARSEM__genmod
