        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:03 2024
        MODULE PRINT_TOTAL_TIME__genmod
          INTERFACE 
            SUBROUTINE PRINT_TOTAL_TIME
            END SUBROUTINE PRINT_TOTAL_TIME
          END INTERFACE 
        END MODULE PRINT_TOTAL_TIME__genmod
