        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE REALLOCATE_MM__genmod
          INTERFACE 
            SUBROUTINE REALLOCATE_MM(NU,NX)
              INTEGER(KIND=4) :: NU
              INTEGER(KIND=4) :: NX
            END SUBROUTINE REALLOCATE_MM
          END INTERFACE 
        END MODULE REALLOCATE_MM__genmod
