        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 15:15:01 2024
        MODULE SB_INIT__genmod
          INTERFACE 
            SUBROUTINE SB_INIT
            END SUBROUTINE SB_INIT
          END INTERFACE 
        END MODULE SB_INIT__genmod
