        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:56:56 2024
        MODULE SET_AA_CASH_INTEGRAL_2__genmod
          INTERFACE 
            SUBROUTINE SET_AA_CASH_INTEGRAL_2(IA,J,I,NF,VAL)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: NF
              REAL(KIND=8) :: VAL
            END SUBROUTINE SET_AA_CASH_INTEGRAL_2
          END INTERFACE 
        END MODULE SET_AA_CASH_INTEGRAL_2__genmod
