        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE SPARSE_MEMORY__genmod
          INTERFACE 
            SUBROUTINE SPARSE_MEMORY(MODE)
              INTEGER(KIND=4) :: MODE
            END SUBROUTINE SPARSE_MEMORY
          END INTERFACE 
        END MODULE SPARSE_MEMORY__genmod
