        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE SPARSE_TO_M__genmod
          INTERFACE 
            SUBROUTINE SPARSE_TO_M
            END SUBROUTINE SPARSE_TO_M
          END INTERFACE 
        END MODULE SPARSE_TO_M__genmod
