        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:19 2024
        MODULE TEST_CP_CINT__genmod
          INTERFACE 
            SUBROUTINE TEST_CP_CINT
            END SUBROUTINE TEST_CP_CINT
          END INTERFACE 
        END MODULE TEST_CP_CINT__genmod
