        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE TEST_MATR_MAXMINCOL__genmod
          INTERFACE 
            SUBROUTINE TEST_MATR_MAXMINCOL
            END SUBROUTINE TEST_MATR_MAXMINCOL
          END INTERFACE 
        END MODULE TEST_MATR_MAXMINCOL__genmod
