        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:16 2024
        MODULE TEST_INVERT_TRM__genmod
          INTERFACE 
            SUBROUTINE TEST_INVERT_TRM(IPART)
              INTEGER(KIND=4) :: IPART
            END SUBROUTINE TEST_INVERT_TRM
          END INTERFACE 
        END MODULE TEST_INVERT_TRM__genmod
