        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:06 2024
        MODULE TEST_INTD__genmod
          INTERFACE 
            SUBROUTINE TEST_INTD
            END SUBROUTINE TEST_INTD
          END INTERFACE 
        END MODULE TEST_INTD__genmod
