        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:03 2024
        MODULE TEST_CLOSING_SLAU__genmod
          INTERFACE 
            SUBROUTINE TEST_CLOSING_SLAU
            END SUBROUTINE TEST_CLOSING_SLAU
          END INTERFACE 
        END MODULE TEST_CLOSING_SLAU__genmod
