        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE TEST_M_DIAGONAL__genmod
          INTERFACE 
            SUBROUTINE TEST_M_DIAGONAL
            END SUBROUTINE TEST_M_DIAGONAL
          END INTERFACE 
        END MODULE TEST_M_DIAGONAL__genmod
