        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:06 2024
        MODULE TEST_INTL__genmod
          INTERFACE 
            SUBROUTINE TEST_INTL
            END SUBROUTINE TEST_INTL
          END INTERFACE 
        END MODULE TEST_INTL__genmod
