        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE WRITE_MATR__genmod
          INTERFACE 
            SUBROUTINE WRITE_MATR
            END SUBROUTINE WRITE_MATR
          END INTERFACE 
        END MODULE WRITE_MATR__genmod
