        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 15:15:01 2024
        MODULE WRITE_ITER_EMPTY__genmod
          INTERFACE 
            FUNCTION WRITE_ITER_EMPTY(STR,TEST)
              CHARACTER(*) :: STR
              LOGICAL(KIND=4) :: TEST
              LOGICAL(KIND=4) :: WRITE_ITER_EMPTY
            END FUNCTION WRITE_ITER_EMPTY
          END INTERFACE 
        END MODULE WRITE_ITER_EMPTY__genmod
