        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE WRITE_MATRIX_MM__genmod
          INTERFACE 
            SUBROUTINE WRITE_MATRIX_MM
            END SUBROUTINE WRITE_MATRIX_MM
          END INTERFACE 
        END MODULE WRITE_MATRIX_MM__genmod
