        !COMPILER-GENERATED INTERFACE MODULE: Fri Apr 05 21:57:02 2024
        MODULE WRITE_MATR_B__genmod
          INTERFACE 
            SUBROUTINE WRITE_MATR_B
            END SUBROUTINE WRITE_MATR_B
          END INTERFACE 
        END MODULE WRITE_MATR_B__genmod
