        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:40 2024
        MODULE ADD_CLOSING_EQ_TO_AREA__genmod
          INTERFACE 
            SUBROUTINE ADD_CLOSING_EQ_TO_AREA(IA,EQ,B)
              INTEGER(KIND=4) :: IA
              REAL(KIND=8) :: EQ(GS%M%NX)
              REAL(KIND=8) :: B
            END SUBROUTINE ADD_CLOSING_EQ_TO_AREA
          END INTERFACE 
        END MODULE ADD_CLOSING_EQ_TO_AREA__genmod
