        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE ADD_EQUATION_TO_MATRIX__genmod
          INTERFACE 
            SUBROUTINE ADD_EQUATION_TO_MATRIX(I,M_EQ,M_B,IA)
              INTEGER(KIND=4) :: I
              REAL(KIND=8) :: M_EQ(GS%M%NX)
              REAL(KIND=8) :: M_B
              INTEGER(KIND=4) :: IA
            END SUBROUTINE ADD_EQUATION_TO_MATRIX
          END INTERFACE 
        END MODULE ADD_EQUATION_TO_MATRIX__genmod
