        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE ALLOCATE_GEOM_DETALE_FOR_NEXT__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_GEOM_DETALE_FOR_NEXT
            END SUBROUTINE ALLOCATE_GEOM_DETALE_FOR_NEXT
          END INTERFACE 
        END MODULE ALLOCATE_GEOM_DETALE_FOR_NEXT__genmod
