        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE ALLOCATE_GEOM_DETALE_FOR_NEXT__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_GEOM_DETALE_FOR_NEXT
            END SUBROUTINE ALLOCATE_GEOM_DETALE_FOR_NEXT
          END INTERFACE 
        END MODULE ALLOCATE_GEOM_DETALE_FOR_NEXT__genmod
