        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE ALLOCATE_BOUNDLINE_GEOM__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_BOUNDLINE_GEOM(IBNDL,INPANEL)
              INTEGER(KIND=4) :: IBNDL
              INTEGER(KIND=4) :: INPANEL
            END SUBROUTINE ALLOCATE_BOUNDLINE_GEOM
          END INTERFACE 
        END MODULE ALLOCATE_BOUNDLINE_GEOM__genmod
