        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE ALLOCATE_AREAVAL__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_AREAVAL(I,MODE)
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: MODE
            END SUBROUTINE ALLOCATE_AREAVAL
          END INTERFACE 
        END MODULE ALLOCATE_AREAVAL__genmod
