        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE ALLOCATE_GU_USE__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_GU_USE
            END SUBROUTINE ALLOCATE_GU_USE
          END INTERFACE 
        END MODULE ALLOCATE_GU_USE__genmod
