        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE ALLOCATE_GU_USE__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_GU_USE
            END SUBROUTINE ALLOCATE_GU_USE
          END INTERFACE 
        END MODULE ALLOCATE_GU_USE__genmod
