        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE ALLOCATE_AREA_GEOM__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_AREA_GEOM(IN,INTR,INPE)
              INTEGER(KIND=4) :: IN
              INTEGER(KIND=4) :: INTR
              INTEGER(KIND=4) :: INPE
            END SUBROUTINE ALLOCATE_AREA_GEOM
          END INTERFACE 
        END MODULE ALLOCATE_AREA_GEOM__genmod
