        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE ALLOCATE_GEOM_DETALE_FOR_NEXT__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_GEOM_DETALE_FOR_NEXT
            END SUBROUTINE ALLOCATE_GEOM_DETALE_FOR_NEXT
          END INTERFACE 
        END MODULE ALLOCATE_GEOM_DETALE_FOR_NEXT__genmod
