        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:23 2024
        MODULE ANGLES_RAZRYV__genmod
          INTERFACE 
            SUBROUTINE ANGLES_RAZRYV(NJ1,ALPHA)
              INTEGER(KIND=4) :: NJ1
              REAL(KIND=8) :: ALPHA(NJ1)
            END SUBROUTINE ANGLES_RAZRYV
          END INTERFACE 
        END MODULE ANGLES_RAZRYV__genmod
