        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE BIND_AREACONST__genmod
          INTERFACE 
            SUBROUTINE BIND_AREACONST(K)
              INTEGER(KIND=4) :: K
            END SUBROUTINE BIND_AREACONST
          END INTERFACE 
        END MODULE BIND_AREACONST__genmod
