        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE BLOCK_DIAGONAL_TO_M__genmod
          INTERFACE 
            SUBROUTINE BLOCK_DIAGONAL_TO_M
            END SUBROUTINE BLOCK_DIAGONAL_TO_M
          END INTERFACE 
        END MODULE BLOCK_DIAGONAL_TO_M__genmod
