        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE BLOCK_DIAGONAL_TO_M__genmod
          INTERFACE 
            SUBROUTINE BLOCK_DIAGONAL_TO_M
            END SUBROUTINE BLOCK_DIAGONAL_TO_M
          END INTERFACE 
        END MODULE BLOCK_DIAGONAL_TO_M__genmod
