        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE BLOCK_DIAGONAL_TO_M__genmod
          INTERFACE 
            SUBROUTINE BLOCK_DIAGONAL_TO_M
            END SUBROUTINE BLOCK_DIAGONAL_TO_M
          END INTERFACE 
        END MODULE BLOCK_DIAGONAL_TO_M__genmod
