        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:03 2024
        MODULE BM_ALLOCATE_BLOCKS__genmod
          INTERFACE 
            SUBROUTINE BM_ALLOCATE_BLOCKS(BM,NB)
              USE SLAU_BLOCK
              TYPE (MAIN_BLOCK_MATRIX) :: BM
              INTEGER(KIND=4) :: NB
            END SUBROUTINE BM_ALLOCATE_BLOCKS
          END INTERFACE 
        END MODULE BM_ALLOCATE_BLOCKS__genmod
