        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:05 2024
        MODULE BM_ALLOCATE_BLOCKS__genmod
          INTERFACE 
            SUBROUTINE BM_ALLOCATE_BLOCKS(BM,NB)
              USE SLAU_BLOCK
              TYPE (MAIN_BLOCK_MATRIX) :: BM
              INTEGER(KIND=4) :: NB
            END SUBROUTINE BM_ALLOCATE_BLOCKS
          END INTERFACE 
        END MODULE BM_ALLOCATE_BLOCKS__genmod
