        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:06 2024
        MODULE BM_BICGSTAB_TEST2__genmod
          INTERFACE 
            SUBROUTINE BM_BICGSTAB_TEST2
            END SUBROUTINE BM_BICGSTAB_TEST2
          END INTERFACE 
        END MODULE BM_BICGSTAB_TEST2__genmod
