        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:03 2024
        MODULE BM_BICGSTAB_TEST2__genmod
          INTERFACE 
            SUBROUTINE BM_BICGSTAB_TEST2
            END SUBROUTINE BM_BICGSTAB_TEST2
          END INTERFACE 
        END MODULE BM_BICGSTAB_TEST2__genmod
