        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:03 2024
        MODULE BM_DEALLOCATE_BLOCK__genmod
          INTERFACE 
            SUBROUTINE BM_DEALLOCATE_BLOCK(B)
              USE SLAU_BLOCK
              TYPE (BLOCK_MATRIX) :: B
            END SUBROUTINE BM_DEALLOCATE_BLOCK
          END INTERFACE 
        END MODULE BM_DEALLOCATE_BLOCK__genmod
