        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:03 2024
        MODULE BM_DEALLOCATE_SPARSE_M__genmod
          INTERFACE 
            SUBROUTINE BM_DEALLOCATE_SPARSE_M(SPARSE)
              USE SLAU_BLOCK
              TYPE (SPARSE_MATRIX) :: SPARSE
            END SUBROUTINE BM_DEALLOCATE_SPARSE_M
          END INTERFACE 
        END MODULE BM_DEALLOCATE_SPARSE_M__genmod
