        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:03 2024
        MODULE BM_DEALLOCATE__genmod
          INTERFACE 
            SUBROUTINE BM_DEALLOCATE(NEED_MM,BM)
              USE SLAU_BLOCK
              LOGICAL(KIND=4) :: NEED_MM
              TYPE (MAIN_BLOCK_MATRIX) :: BM
            END SUBROUTINE BM_DEALLOCATE
          END INTERFACE 
        END MODULE BM_DEALLOCATE__genmod
