        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:03 2024
        MODULE BM_INIT_BLOCK_MATRIX__genmod
          INTERFACE 
            SUBROUTINE BM_INIT_BLOCK_MATRIX(BM)
              USE SLAU_BLOCK
              TYPE (MAIN_BLOCK_MATRIX) ,TARGET :: BM
            END SUBROUTINE BM_INIT_BLOCK_MATRIX
          END INTERFACE 
        END MODULE BM_INIT_BLOCK_MATRIX__genmod
