        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:03 2024
        MODULE BM_ILU_TEST__genmod
          INTERFACE 
            SUBROUTINE BM_ILU_TEST
            END SUBROUTINE BM_ILU_TEST
          END INTERFACE 
        END MODULE BM_ILU_TEST__genmod
