        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:03 2024
        MODULE BM_MAIN_BLOCK_SPARSE__genmod
          INTERFACE 
            SUBROUTINE BM_MAIN_BLOCK_SPARSE(BM)
              USE SLAU_BLOCK
              TYPE (MAIN_BLOCK_MATRIX) ,TARGET :: BM
            END SUBROUTINE BM_MAIN_BLOCK_SPARSE
          END INTERFACE 
        END MODULE BM_MAIN_BLOCK_SPARSE__genmod
