        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:05 2024
        MODULE BM_M_TO_BLOCK_DIAGONAL__genmod
          INTERFACE 
            SUBROUTINE BM_M_TO_BLOCK_DIAGONAL(M,BM)
              USE SLAU_BLOCK
              REAL(KIND=8) :: M(:,:)
              TYPE (MAIN_BLOCK_MATRIX) ,TARGET :: BM
            END SUBROUTINE BM_M_TO_BLOCK_DIAGONAL
          END INTERFACE 
        END MODULE BM_M_TO_BLOCK_DIAGONAL__genmod
