        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:03 2024
        MODULE BM_NULL_MROW__genmod
          INTERFACE 
            SUBROUTINE BM_NULL_MROW(MROW)
              USE SLAU_BLOCK
              TYPE (SPARSE_MATRIX_ROW) :: MROW
            END SUBROUTINE BM_NULL_MROW
          END INTERFACE 
        END MODULE BM_NULL_MROW__genmod
