        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:03 2024
        MODULE BM_REALLOCATE_BLOCK__genmod
          INTERFACE 
            SUBROUTINE BM_REALLOCATE_BLOCK(B,NU,NX)
              USE SLAU_BLOCK
              TYPE (BLOCK_MATRIX) :: B
              INTEGER(KIND=4) :: NU
              INTEGER(KIND=4) :: NX
            END SUBROUTINE BM_REALLOCATE_BLOCK
          END INTERFACE 
        END MODULE BM_REALLOCATE_BLOCK__genmod
