        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:05 2024
        MODULE BM_SWAP_VECTOR_P__genmod
          INTERFACE 
            SUBROUTINE BM_SWAP_VECTOR_P(BM,X)
              USE SLAU_BLOCK
              TYPE (MAIN_BLOCK_MATRIX) ,TARGET :: BM
              REAL(KIND=8) :: X(:)
            END SUBROUTINE BM_SWAP_VECTOR_P
          END INTERFACE 
        END MODULE BM_SWAP_VECTOR_P__genmod
