        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 05 10:16:35 2025
        MODULE BUILD_BOUND__genmod
          INTERFACE 
            SUBROUTINE BUILD_BOUND
            END SUBROUTINE BUILD_BOUND
          END INTERFACE 
        END MODULE BUILD_BOUND__genmod
