        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 05 10:16:35 2025
        MODULE BUILD_CURVE__genmod
          INTERFACE 
            SUBROUTINE BUILD_CURVE
            END SUBROUTINE BUILD_CURVE
          END INTERFACE 
        END MODULE BUILD_CURVE__genmod
