        !COMPILER-GENERATED INTERFACE MODULE: Sun Dec 01 19:15:53 2024
        MODULE BUILD_BOUND__genmod
          INTERFACE 
            SUBROUTINE BUILD_BOUND
            END SUBROUTINE BUILD_BOUND
          END INTERFACE 
        END MODULE BUILD_BOUND__genmod
