        !COMPILER-GENERATED INTERFACE MODULE: Sun Dec 22 15:56:17 2024
        MODULE BUILD_BOUND__genmod
          INTERFACE 
            SUBROUTINE BUILD_BOUND
            END SUBROUTINE BUILD_BOUND
          END INTERFACE 
        END MODULE BUILD_BOUND__genmod
