        !COMPILER-GENERATED INTERFACE MODULE: Sun Dec 01 19:15:53 2024
        MODULE BUILD_CURVE__genmod
          INTERFACE 
            SUBROUTINE BUILD_CURVE
            END SUBROUTINE BUILD_CURVE
          END INTERFACE 
        END MODULE BUILD_CURVE__genmod
