        !COMPILER-GENERATED INTERFACE MODULE: Sun Dec 22 15:56:17 2024
        MODULE BUILD_CURVE__genmod
          INTERFACE 
            SUBROUTINE BUILD_CURVE
            END SUBROUTINE BUILD_CURVE
          END INTERFACE 
        END MODULE BUILD_CURVE__genmod
