        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:07:54 2024
        MODULE CALCINT_NF1011__genmod
          INTERFACE 
            FUNCTION CALCINT_NF1011(Z0,Z1,Z2,NF)
              COMPLEX(KIND=8) :: Z0
              COMPLEX(KIND=8) :: Z1
              COMPLEX(KIND=8) :: Z2
              INTEGER(KIND=4) :: NF
              REAL(KIND=8) :: CALCINT_NF1011
            END FUNCTION CALCINT_NF1011
          END INTERFACE 
        END MODULE CALCINT_NF1011__genmod
