        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:28 2024
        MODULE CALCINT_NF1011_2__genmod
          INTERFACE 
            SUBROUTINE CALCINT_NF1011_2(Z0,Z1,Z2,VAL,VAL2)
              COMPLEX(KIND=8) :: Z0
              COMPLEX(KIND=8) :: Z1
              COMPLEX(KIND=8) :: Z2
              REAL(KIND=8) :: VAL
              REAL(KIND=8) :: VAL2
            END SUBROUTINE CALCINT_NF1011_2
          END INTERFACE 
        END MODULE CALCINT_NF1011_2__genmod
