        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:28 2024
        MODULE CALCINT_NF1011Z__genmod
          INTERFACE 
            SUBROUTINE CALCINT_NF1011Z(Z0,Z1,Z2,FZ1,FZ2,FZ3)
              COMPLEX(KIND=8) :: Z0
              COMPLEX(KIND=8) :: Z1
              COMPLEX(KIND=8) :: Z2
              COMPLEX(KIND=8) :: FZ1
              COMPLEX(KIND=8) :: FZ2
              COMPLEX(KIND=8) :: FZ3
            END SUBROUTINE CALCINT_NF1011Z
          END INTERFACE 
        END MODULE CALCINT_NF1011Z__genmod
