        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:15 2024
        MODULE CLOSING_CHEKING__genmod
          INTERFACE 
            SUBROUTINE CLOSING_CHEKING
            END SUBROUTINE CLOSING_CHEKING
          END INTERFACE 
        END MODULE CLOSING_CHEKING__genmod
