        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 12 23:25:44 2024
        MODULE CLOSING_3__genmod
          INTERFACE 
            SUBROUTINE CLOSING_3(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE CLOSING_3
          END INTERFACE 
        END MODULE CLOSING_3__genmod
