        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 15 13:53:02 2024
        MODULE CLOSING_3__genmod
          INTERFACE 
            SUBROUTINE CLOSING_3(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE CLOSING_3
          END INTERFACE 
        END MODULE CLOSING_3__genmod
