        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:15 2024
        MODULE CLOSING__genmod
          INTERFACE 
            SUBROUTINE CLOSING(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE CLOSING
          END INTERFACE 
        END MODULE CLOSING__genmod
