        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 15 13:53:02 2024
        MODULE CLOSING_CHEKING__genmod
          INTERFACE 
            SUBROUTINE CLOSING_CHEKING
            END SUBROUTINE CLOSING_CHEKING
          END INTERFACE 
        END MODULE CLOSING_CHEKING__genmod
