        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 12 23:25:44 2024
        MODULE CLOSING_CHEKING__genmod
          INTERFACE 
            SUBROUTINE CLOSING_CHEKING
            END SUBROUTINE CLOSING_CHEKING
          END INTERFACE 
        END MODULE CLOSING_CHEKING__genmod
