        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 12 23:25:44 2024
        MODULE CLOSING__genmod
          INTERFACE 
            SUBROUTINE CLOSING(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE CLOSING
          END INTERFACE 
        END MODULE CLOSING__genmod
