        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 15 13:53:02 2024
        MODULE CLOSING_2__genmod
          INTERFACE 
            SUBROUTINE CLOSING_2(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE CLOSING_2
          END INTERFACE 
        END MODULE CLOSING_2__genmod
