        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:37 2024
        MODULE CP_CALCINT_NF45Z__genmod
          INTERFACE 
            FUNCTION CP_CALCINT_NF45Z(ZTC,R,MODE)
              COMPLEX(KIND=8) :: ZTC
              REAL(KIND=8) :: R
              INTEGER(KIND=4) :: MODE
              COMPLEX(KIND=8) :: CP_CALCINT_NF45Z
            END FUNCTION CP_CALCINT_NF45Z
          END INTERFACE 
        END MODULE CP_CALCINT_NF45Z__genmod
