        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:13 2024
        MODULE CP_CALCINT_NF1011__genmod
          INTERFACE 
            FUNCTION CP_CALCINT_NF1011(ZTC,R,MODE,NF)
              COMPLEX(KIND=8) :: ZTC
              REAL(KIND=8) :: R
              INTEGER(KIND=4) :: MODE
              INTEGER(KIND=4) :: NF
              REAL(KIND=8) :: CP_CALCINT_NF1011
            END FUNCTION CP_CALCINT_NF1011
          END INTERFACE 
        END MODULE CP_CALCINT_NF1011__genmod
