        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE DEALLOCATE_GU_GEN__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_GU_GEN(GUG)
              USE PGMOD
              TYPE (TBOUNGLINE_GU_GEN) :: GUG
            END SUBROUTINE DEALLOCATE_GU_GEN
          END INTERFACE 
        END MODULE DEALLOCATE_GU_GEN__genmod
