        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:17 2024
        MODULE DEALLOCATE_BOUND_GU__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUND_GU(IA,IBND)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
            END SUBROUTINE DEALLOCATE_BOUND_GU
          END INTERFACE 
        END MODULE DEALLOCATE_BOUND_GU__genmod
