        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE DEALLOCATE_AREAPART__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_AREAPART(IA,IPART)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IPART
            END SUBROUTINE DEALLOCATE_AREAPART
          END INTERFACE 
        END MODULE DEALLOCATE_AREAPART__genmod
