        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE DEALLOCATE_MM__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_MM(NEED_MM)
              LOGICAL(KIND=4) :: NEED_MM
            END SUBROUTINE DEALLOCATE_MM
          END INTERFACE 
        END MODULE DEALLOCATE_MM__genmod
