        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE DEALLOCATE_AREA_COLLOCATE_POINTS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_AREA_COLLOCATE_POINTS(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_AREA_COLLOCATE_POINTS
          END INTERFACE 
        END MODULE DEALLOCATE_AREA_COLLOCATE_POINTS__genmod
