        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE DEALLOCATE_AREA__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_AREA(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_AREA
          END INTERFACE 
        END MODULE DEALLOCATE_AREA__genmod
