        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE DEALLOCATE_CASH__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_CASH(CASH)
              USE PGMOD
              TYPE (TCASH) :: CASH
            END SUBROUTINE DEALLOCATE_CASH
          END INTERFACE 
        END MODULE DEALLOCATE_CASH__genmod
