        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE DEALLOCATE_BOUNDS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUNDS(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_BOUNDS
          END INTERFACE 
        END MODULE DEALLOCATE_BOUNDS__genmod
