        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:17 2024
        MODULE DEALLOCATE_DOMAINS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_DOMAINS
            END SUBROUTINE DEALLOCATE_DOMAINS
          END INTERFACE 
        END MODULE DEALLOCATE_DOMAINS__genmod
