        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE DEALLOCATE_GU_GENGLOBAL__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_GU_GENGLOBAL(GUG)
              USE PGMOD
              TYPE (TBOUNGLINE_GU_GENGLOBAL) :: GUG
            END SUBROUTINE DEALLOCATE_GU_GENGLOBAL
          END INTERFACE 
        END MODULE DEALLOCATE_GU_GENGLOBAL__genmod
