        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE DEALLOCATE_AREAPART__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_AREAPART(IA,IPART)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IPART
            END SUBROUTINE DEALLOCATE_AREAPART
          END INTERFACE 
        END MODULE DEALLOCATE_AREAPART__genmod
