        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE DEALLOCATE_BOUNDS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUNDS(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_BOUNDS
          END INTERFACE 
        END MODULE DEALLOCATE_BOUNDS__genmod
