        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:17 2024
        MODULE DEALLOCATE_DOMAIN_GU__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_DOMAIN_GU(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_DOMAIN_GU
          END INTERFACE 
        END MODULE DEALLOCATE_DOMAIN_GU__genmod
