        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE DEALLOCATE_CASHINTEGRALS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_CASHINTEGRALS(C)
              USE PGMOD
              TYPE (TCASHINTEGRAL) :: C
            END SUBROUTINE DEALLOCATE_CASHINTEGRALS
          END INTERFACE 
        END MODULE DEALLOCATE_CASHINTEGRALS__genmod
