        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE DEALLOCATE_BOUNDLINE__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUNDLINE(IA,IBND,IBNDL)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE DEALLOCATE_BOUNDLINE
          END INTERFACE 
        END MODULE DEALLOCATE_BOUNDLINE__genmod
