        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:17 2024
        MODULE DEALLOCATE_BOUNDLINES__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUNDLINES(IA,IBND)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
            END SUBROUTINE DEALLOCATE_BOUNDLINES
          END INTERFACE 
        END MODULE DEALLOCATE_BOUNDLINES__genmod
