        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE DEALLOCATE_CASH__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_CASH(CASH)
              USE PGMOD
              TYPE (TCASH) :: CASH
            END SUBROUTINE DEALLOCATE_CASH
          END INTERFACE 
        END MODULE DEALLOCATE_CASH__genmod
