        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE DEALLOCATE_COL_INFO__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_COL_INFO(CI)
              USE PGMOD
              TYPE (COL_INFO) :: CI
            END SUBROUTINE DEALLOCATE_COL_INFO
          END INTERFACE 
        END MODULE DEALLOCATE_COL_INFO__genmod
