        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE DEALLOCATE_BOUND_COLLOCATE_POINTS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUND_COLLOCATE_POINTS(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_BOUND_COLLOCATE_POINTS
          END INTERFACE 
        END MODULE DEALLOCATE_BOUND_COLLOCATE_POINTS__genmod
