        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE DEALLOCATE_DOMAIN_GU__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_DOMAIN_GU(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_DOMAIN_GU
          END INTERFACE 
        END MODULE DEALLOCATE_DOMAIN_GU__genmod
