        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:17 2024
        MODULE DEALLOCATE_BOUNDLINE2__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUNDLINE2(IA,IBND,IBNDL)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE DEALLOCATE_BOUNDLINE2
          END INTERFACE 
        END MODULE DEALLOCATE_BOUNDLINE2__genmod
