        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE DEALLOCATE_DOMAINS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_DOMAINS
            END SUBROUTINE DEALLOCATE_DOMAINS
          END INTERFACE 
        END MODULE DEALLOCATE_DOMAINS__genmod
