        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE DEALLOCATE_AREA__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_AREA(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_AREA
          END INTERFACE 
        END MODULE DEALLOCATE_AREA__genmod
