        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE DEALLOCATE_GU_GENGLOBAL__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_GU_GENGLOBAL(GUG)
              USE PGMOD
              TYPE (TBOUNGLINE_GU_GENGLOBAL) :: GUG
            END SUBROUTINE DEALLOCATE_GU_GENGLOBAL
          END INTERFACE 
        END MODULE DEALLOCATE_GU_GENGLOBAL__genmod
