        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE DEALLOCATE_BOUND_GU__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUND_GU(IA,IBND)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
            END SUBROUTINE DEALLOCATE_BOUND_GU
          END INTERFACE 
        END MODULE DEALLOCATE_BOUND_GU__genmod
