        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE DEALLOCATE_BOUNDLINES__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUNDLINES(IA,IBND)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
            END SUBROUTINE DEALLOCATE_BOUNDLINES
          END INTERFACE 
        END MODULE DEALLOCATE_BOUNDLINES__genmod
