        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE DEALLOCATE_GU_GEN__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_GU_GEN(GUG)
              USE PGMOD
              TYPE (TBOUNGLINE_GU_GEN) :: GUG
            END SUBROUTINE DEALLOCATE_GU_GEN
          END INTERFACE 
        END MODULE DEALLOCATE_GU_GEN__genmod
