        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE DEALLOCATE_BOUND_COLLOCATE_POINTS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_BOUND_COLLOCATE_POINTS(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE DEALLOCATE_BOUND_COLLOCATE_POINTS
          END INTERFACE 
        END MODULE DEALLOCATE_BOUND_COLLOCATE_POINTS__genmod
