        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE DEALLOCATE_DOMAINS__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_DOMAINS
            END SUBROUTINE DEALLOCATE_DOMAINS
          END INTERFACE 
        END MODULE DEALLOCATE_DOMAINS__genmod
