        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE DEALLOCATE_GA__genmod
          INTERFACE 
            SUBROUTINE DEALLOCATE_GA(IA,IBND,IBNDL,IGA)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
              INTEGER(KIND=4) :: IBNDL
              INTEGER(KIND=4) :: IGA
            END SUBROUTINE DEALLOCATE_GA
          END INTERFACE 
        END MODULE DEALLOCATE_GA__genmod
