        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:12 2024
        MODULE DISTANCETOPOINT__genmod
          INTERFACE 
            FUNCTION DISTANCETOPOINT(X1,Y1,X2,Y2)
              REAL(KIND=8) :: X1
              REAL(KIND=8) :: Y1
              REAL(KIND=8) :: X2
              REAL(KIND=8) :: Y2
              REAL(KIND=8) :: DISTANCETOPOINT
            END FUNCTION DISTANCETOPOINT
          END INTERFACE 
        END MODULE DISTANCETOPOINT__genmod
