        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 26 11:02:20 2024
        MODULE DRAW_SQUARE__genmod
          INTERFACE 
            SUBROUTINE DRAW_SQUARE(G1)
              INTEGER(KIND=4) :: G1
            END SUBROUTINE DRAW_SQUARE
          END INTERFACE 
        END MODULE DRAW_SQUARE__genmod
