        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 23 23:31:52 2024
        MODULE DRAW_SQUARE__genmod
          INTERFACE 
            SUBROUTINE DRAW_SQUARE
            END SUBROUTINE DRAW_SQUARE
          END INTERFACE 
        END MODULE DRAW_SQUARE__genmod
