        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 15 13:53:02 2024
        MODULE DRAW_SQUARE_CHEKING__genmod
          INTERFACE 
            SUBROUTINE DRAW_SQUARE_CHEKING
            END SUBROUTINE DRAW_SQUARE_CHEKING
          END INTERFACE 
        END MODULE DRAW_SQUARE_CHEKING__genmod
