        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 26 11:02:20 2024
        MODULE DRAW_SQUARE_CHEKING__genmod
          INTERFACE 
            SUBROUTINE DRAW_SQUARE_CHEKING
            END SUBROUTINE DRAW_SQUARE_CHEKING
          END INTERFACE 
        END MODULE DRAW_SQUARE_CHEKING__genmod
