        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 15 13:53:02 2024
        MODULE DRAW__genmod
          INTERFACE 
            SUBROUTINE DRAW(G1,NUMBER_TASK)
              INTEGER(KIND=4) :: G1
              INTEGER(KIND=4) :: NUMBER_TASK
            END SUBROUTINE DRAW
          END INTERFACE 
        END MODULE DRAW__genmod
