        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:15 2024
        MODULE DRAW_SQUARE_CHEKING__genmod
          INTERFACE 
            SUBROUTINE DRAW_SQUARE_CHEKING
            END SUBROUTINE DRAW_SQUARE_CHEKING
          END INTERFACE 
        END MODULE DRAW_SQUARE_CHEKING__genmod
