        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 05 10:16:35 2025
        MODULE DRAW_CURVES__genmod
          INTERFACE 
            SUBROUTINE DRAW_CURVES
            END SUBROUTINE DRAW_CURVES
          END INTERFACE 
        END MODULE DRAW_CURVES__genmod
