        !COMPILER-GENERATED INTERFACE MODULE: Sun Dec 22 15:56:17 2024
        MODULE DRAW_CURVES__genmod
          INTERFACE 
            SUBROUTINE DRAW_CURVES
            END SUBROUTINE DRAW_CURVES
          END INTERFACE 
        END MODULE DRAW_CURVES__genmod
