        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE DRW_MATRIX__genmod
          INTERFACE 
            SUBROUTINE DRW_MATRIX
            END SUBROUTINE DRW_MATRIX
          END INTERFACE 
        END MODULE DRW_MATRIX__genmod
