        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE DRW_MATRIX__genmod
          INTERFACE 
            SUBROUTINE DRW_MATRIX
            END SUBROUTINE DRW_MATRIX
          END INTERFACE 
        END MODULE DRW_MATRIX__genmod
