        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:33 2024
        MODULE END_WRITE_BY_TIME__genmod
          INTERFACE 
            SUBROUTINE END_WRITE_BY_TIME
            END SUBROUTINE END_WRITE_BY_TIME
          END INTERFACE 
        END MODULE END_WRITE_BY_TIME__genmod
