        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE END_WRITE_BY_TIME__genmod
          INTERFACE 
            SUBROUTINE END_WRITE_BY_TIME
            END SUBROUTINE END_WRITE_BY_TIME
          END INTERFACE 
        END MODULE END_WRITE_BY_TIME__genmod
