        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE END_WRITE_BY_TIME__genmod
          INTERFACE 
            SUBROUTINE END_WRITE_BY_TIME
            END SUBROUTINE END_WRITE_BY_TIME
          END INTERFACE 
        END MODULE END_WRITE_BY_TIME__genmod
