        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 15 13:53:02 2024
        MODULE ERROR__genmod
          INTERFACE 
            SUBROUTINE ERROR(NUMBER_TASK,BOUND)
              INTEGER(KIND=4) :: NUMBER_TASK
              INTEGER(KIND=4) :: BOUND
            END SUBROUTINE ERROR
          END INTERFACE 
        END MODULE ERROR__genmod
