        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE FREE_OMP_BUFFER__genmod
          INTERFACE 
            SUBROUTINE FREE_OMP_BUFFER
            END SUBROUTINE FREE_OMP_BUFFER
          END INTERFACE 
        END MODULE FREE_OMP_BUFFER__genmod
