        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE FREE_OMP_BUFFER__genmod
          INTERFACE 
            SUBROUTINE FREE_OMP_BUFFER
            END SUBROUTINE FREE_OMP_BUFFER
          END INTERFACE 
        END MODULE FREE_OMP_BUFFER__genmod
