        !COMPILER-GENERATED INTERFACE MODULE: Sun Dec 22 15:56:17 2024
        MODULE FUNCTION_IMPACT_TESTING__genmod
          INTERFACE 
            FUNCTION FUNCTION_IMPACT_TESTING(N,Y,DLT)
              INTEGER(KIND=4) :: N
              REAL(KIND=8) :: Y(N)
              REAL(KIND=8) :: DLT
              INTEGER(KIND=4) :: FUNCTION_IMPACT_TESTING
            END FUNCTION FUNCTION_IMPACT_TESTING
          END INTERFACE 
        END MODULE FUNCTION_IMPACT_TESTING__genmod
