        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:20 2024
        MODULE GA_DRW_TRMESH_FUNC_ZONE2__genmod
          INTERFACE 
            SUBROUTINE GA_DRW_TRMESH_FUNC_ZONE2(IA,IFILE,ZONENAME,      &
     &WRITE_POINT)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IFILE
              CHARACTER(*) :: ZONENAME
              EXTERNAL WRITE_POINT
            END SUBROUTINE GA_DRW_TRMESH_FUNC_ZONE2
          END INTERFACE 
        END MODULE GA_DRW_TRMESH_FUNC_ZONE2__genmod
