        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:33 2024
        MODULE GA_DRW_TRMESH_FUNC__genmod
          INTERFACE 
            SUBROUTINE GA_DRW_TRMESH_FUNC(FILENAME,VARS,WRITE_POINT)
              CHARACTER(*) :: FILENAME
              CHARACTER(*) :: VARS
              EXTERNAL WRITE_POINT
            END SUBROUTINE GA_DRW_TRMESH_FUNC
          END INTERFACE 
        END MODULE GA_DRW_TRMESH_FUNC__genmod
