        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:20 2024
        MODULE GA_GET_FORCE_BL2__genmod
          INTERFACE 
            SUBROUTINE GA_GET_FORCE_BL2(IB,FX,FY)
              INTEGER(KIND=4) :: IB
              REAL(KIND=8) :: FX
              REAL(KIND=8) :: FY
            END SUBROUTINE GA_GET_FORCE_BL2
          END INTERFACE 
        END MODULE GA_GET_FORCE_BL2__genmod
