        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:20 2024
        MODULE GA_GETFOURIERBOUNLINEFUNCAPPROX__genmod
          INTERFACE 
            SUBROUTINE GA_GETFOURIERBOUNLINEFUNCAPPROX(PSIOM,N,GA)
              USE PGMOD
              INTEGER(KIND=4) :: N
              REAL(KIND=8) :: PSIOM(N)
              TYPE (TBOUNLINEFUNCAPPROX) :: GA
            END SUBROUTINE GA_GETFOURIERBOUNLINEFUNCAPPROX
          END INTERFACE 
        END MODULE GA_GETFOURIERBOUNLINEFUNCAPPROX__genmod
