        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:32 2024
        MODULE GA_GETFOURIERBOUNLINEFUNCCOEF__genmod
          INTERFACE 
            SUBROUTINE GA_GETFOURIERBOUNLINEFUNCCOEF(PSIOM,N,COEF)
              INTEGER(KIND=4) :: N
              REAL(KIND=8) :: PSIOM(N)
              REAL(KIND=8) :: COEF(N)
            END SUBROUTINE GA_GETFOURIERBOUNLINEFUNCCOEF
          END INTERFACE 
        END MODULE GA_GETFOURIERBOUNLINEFUNCCOEF__genmod
