        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:20 2024
        MODULE GA_GETFOURIERBOUNLINEFUNCAPPROX_TESTHALF__genmod
          INTERFACE 
            SUBROUTINE GA_GETFOURIERBOUNLINEFUNCAPPROX_TESTHALF(PSIOM,N,&
     &GA,IS_HALF)
              USE PGMOD
              INTEGER(KIND=4) :: N
              REAL(KIND=8) :: PSIOM(N)
              TYPE (TBOUNLINEFUNCAPPROX) :: GA
              LOGICAL(KIND=4) :: IS_HALF
            END SUBROUTINE GA_GETFOURIERBOUNLINEFUNCAPPROX_TESTHALF
          END INTERFACE 
        END MODULE GA_GETFOURIERBOUNLINEFUNCAPPROX_TESTHALF__genmod
