        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:33 2024
        MODULE GA_GET_FORCE_CIRCLE__genmod
          INTERFACE 
            SUBROUTINE GA_GET_FORCE_CIRCLE(IB,FX,FY)
              INTEGER(KIND=4) :: IB
              REAL(KIND=8) :: FX
              REAL(KIND=8) :: FY
            END SUBROUTINE GA_GET_FORCE_CIRCLE
          END INTERFACE 
        END MODULE GA_GET_FORCE_CIRCLE__genmod
