        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:36:16 2024
        MODULE GA_GET_FORCE_CIRCLE_BL__genmod
          INTERFACE 
            SUBROUTINE GA_GET_FORCE_CIRCLE_BL(IB,IBL,FX,FY)
              INTEGER(KIND=4) :: IB
              INTEGER(KIND=4) :: IBL
              REAL(KIND=8) :: FX
              REAL(KIND=8) :: FY
            END SUBROUTINE GA_GET_FORCE_CIRCLE_BL
          END INTERFACE 
        END MODULE GA_GET_FORCE_CIRCLE_BL__genmod
