        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:33 2024
        MODULE GA_GRADP_BOUNDLINE__genmod
          INTERFACE 
            FUNCTION GA_GRADP_BOUNDLINE(IB,IBL) RESULT(F)
              INTEGER(KIND=4) :: IB
              INTEGER(KIND=4) :: IBL
              REAL(KIND=8) :: F
            END FUNCTION GA_GRADP_BOUNDLINE
          END INTERFACE 
        END MODULE GA_GRADP_BOUNDLINE__genmod
