        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:20 2024
        MODULE GA_INIT_GEOM_CYLIDER_PARTICLE2__genmod
          INTERFACE 
            SUBROUTINE GA_INIT_GEOM_CYLIDER_PARTICLE2(X0,Y0,R0,TYPE_GA, &
     &NSN,N_SHIFT)
              REAL(KIND=8) :: X0
              REAL(KIND=8) :: Y0
              REAL(KIND=8) :: R0
              INTEGER(KIND=4) :: TYPE_GA
              INTEGER(KIND=4) :: NSN
              INTEGER(KIND=4) :: N_SHIFT
            END SUBROUTINE GA_INIT_GEOM_CYLIDER_PARTICLE2
          END INTERFACE 
        END MODULE GA_INIT_GEOM_CYLIDER_PARTICLE2__genmod
