        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:20 2024
        MODULE GA_READMESHVTK__genmod
          INTERFACE 
            SUBROUTINE GA_READMESHVTK(FNAME)
              CHARACTER(*) :: FNAME
            END SUBROUTINE GA_READMESHVTK
          END INTERFACE 
        END MODULE GA_READMESHVTK__genmod
