        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:33 2024
        MODULE GA_READMESHMSH__genmod
          INTERFACE 
            SUBROUTINE GA_READMESHMSH(FNAME)
              CHARACTER(*) :: FNAME
            END SUBROUTINE GA_READMESHMSH
          END INTERFACE 
        END MODULE GA_READMESHMSH__genmod
