        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:36:16 2024
        MODULE GA_READMESHMSH__genmod
          INTERFACE 
            SUBROUTINE GA_READMESHMSH(FNAME)
              CHARACTER(*) :: FNAME
            END SUBROUTINE GA_READMESHMSH
          END INTERFACE 
        END MODULE GA_READMESHMSH__genmod
