        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:20 2024
        MODULE GA_READMESHMSH__genmod
          INTERFACE 
            SUBROUTINE GA_READMESHMSH(FNAME)
              CHARACTER(*) :: FNAME
            END SUBROUTINE GA_READMESHMSH
          END INTERFACE 
        END MODULE GA_READMESHMSH__genmod
