        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:33 2024
        MODULE GAGRADP_ONELINE_BASE__genmod
          INTERFACE 
            FUNCTION GAGRADP_ONELINE_BASE(IFS) RESULT(DP)
              USE PGMOD
              TYPE (INTF_STRUCT) :: IFS
              REAL(KIND=8) :: DP
            END FUNCTION GAGRADP_ONELINE_BASE
          END INTERFACE 
        END MODULE GAGRADP_ONELINE_BASE__genmod
