        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:32 2024
        MODULE GAINTF_FREE__genmod
          INTERFACE 
            SUBROUTINE GAINTF_FREE(IFS)
              USE PGMOD
              TYPE (INTF_STRUCT) :: IFS
            END SUBROUTINE GAINTF_FREE
          END INTERFACE 
        END MODULE GAINTF_FREE__genmod
