        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:20 2024
        MODULE GAINTF_FREE__genmod
          INTERFACE 
            SUBROUTINE GAINTF_FREE(IFS)
              USE PGMOD
              TYPE (INTF_STRUCT) :: IFS
            END SUBROUTINE GAINTF_FREE
          END INTERFACE 
        END MODULE GAINTF_FREE__genmod
