        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:10 2024
        MODULE GEOM_COLLOCATE_POINTS_AREA__genmod
          INTERFACE 
            SUBROUTINE GEOM_COLLOCATE_POINTS_AREA
            END SUBROUTINE GEOM_COLLOCATE_POINTS_AREA
          END INTERFACE 
        END MODULE GEOM_COLLOCATE_POINTS_AREA__genmod
