        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:11 2024
        MODULE GEOM_DETALE_POSTPROCESSOR__genmod
          INTERFACE 
            SUBROUTINE GEOM_DETALE_POSTPROCESSOR(IB)
              INTEGER(KIND=4) :: IB
            END SUBROUTINE GEOM_DETALE_POSTPROCESSOR
          END INTERFACE 
        END MODULE GEOM_DETALE_POSTPROCESSOR__genmod
