        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:29 2024
        MODULE GEOM_DETALE_POSTPROCESSOR__genmod
          INTERFACE 
            SUBROUTINE GEOM_DETALE_POSTPROCESSOR(IB)
              INTEGER(KIND=4) :: IB
            END SUBROUTINE GEOM_DETALE_POSTPROCESSOR
          END INTERFACE 
        END MODULE GEOM_DETALE_POSTPROCESSOR__genmod
