        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:33 2024
        MODULE GET_TOTAL_TIME__genmod
          INTERFACE 
            FUNCTION GET_TOTAL_TIME
              REAL(KIND=8) :: GET_TOTAL_TIME
            END FUNCTION GET_TOTAL_TIME
          END INTERFACE 
        END MODULE GET_TOTAL_TIME__genmod
