        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE GET_IND_COSTVALIND__genmod
          INTERFACE 
            SUBROUTINE GET_IND_COSTVALIND(IND,J,IA)
              INTEGER(KIND=4) :: IND
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: IA
            END SUBROUTINE GET_IND_COSTVALIND
          END INTERFACE 
        END MODULE GET_IND_COSTVALIND__genmod
