        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE GET_IND_COSTVALIND__genmod
          INTERFACE 
            SUBROUTINE GET_IND_COSTVALIND(IND,J,IA)
              INTEGER(KIND=4) :: IND
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: IA
            END SUBROUTINE GET_IND_COSTVALIND
          END INTERFACE 
        END MODULE GET_IND_COSTVALIND__genmod
