        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE GET_MATRIX_AREA_AP__genmod
          INTERFACE 
            SUBROUTINE GET_MATRIX_AREA_AP(IA,ICP,FUNC_INF)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: ICP
              REAL(KIND=8) :: FUNC_INF
              EXTERNAL FUNC_INF
            END SUBROUTINE GET_MATRIX_AREA_AP
          END INTERFACE 
        END MODULE GET_MATRIX_AREA_AP__genmod
