        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE GET_IND_AREA3__genmod
          INTERFACE 
            SUBROUTINE GET_IND_AREA3
            END SUBROUTINE GET_IND_AREA3
          END INTERFACE 
        END MODULE GET_IND_AREA3__genmod
