        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:25 2024
        MODULE GET_MATRIX_AREA__genmod
          INTERFACE 
            SUBROUTINE GET_MATRIX_AREA(IA,FUNC_INF)
              INTEGER(KIND=4) :: IA
              REAL(KIND=8) :: FUNC_INF
              EXTERNAL FUNC_INF
            END SUBROUTINE GET_MATRIX_AREA
          END INTERFACE 
        END MODULE GET_MATRIX_AREA__genmod
