        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE GET_BB_CASH_INTEGRAL__genmod
          INTERFACE 
            FUNCTION GET_BB_CASH_INTEGRAL(IA,KND,J,KND0,I,NF)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: KND
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: KND0
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: NF
              REAL(KIND=8) :: GET_BB_CASH_INTEGRAL
            END FUNCTION GET_BB_CASH_INTEGRAL
          END INTERFACE 
        END MODULE GET_BB_CASH_INTEGRAL__genmod
