        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:22 2024
        MODULE GET_ARVAL_FUNP__genmod
          INTERFACE 
            SUBROUTINE GET_ARVAL_FUNP(KU,KND)
              INTEGER(KIND=4) :: KU
              INTEGER(KIND=4) :: KND
            END SUBROUTINE GET_ARVAL_FUNP
          END INTERFACE 
        END MODULE GET_ARVAL_FUNP__genmod
