        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE GET_IND_AREA__genmod
          INTERFACE 
            SUBROUTINE GET_IND_AREA(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE GET_IND_AREA
          END INTERFACE 
        END MODULE GET_IND_AREA__genmod
