        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:35 2024
        MODULE GET_PSIOML__genmod
          INTERFACE 
            SUBROUTINE GET_PSIOML(IA,KND)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: KND
            END SUBROUTINE GET_PSIOML
          END INTERFACE 
        END MODULE GET_PSIOML__genmod
