        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE GS_PRINT_STOP__genmod
          INTERFACE 
            SUBROUTINE GS_PRINT_STOP(S)
              CHARACTER(*) :: S
            END SUBROUTINE GS_PRINT_STOP
          END INTERFACE 
        END MODULE GS_PRINT_STOP__genmod
