        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE GS_PRINTINIT_CASH__genmod
          INTERFACE 
            SUBROUTINE GS_PRINTINIT_CASH
            END SUBROUTINE GS_PRINTINIT_CASH
          END INTERFACE 
        END MODULE GS_PRINTINIT_CASH__genmod
