        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE GS_PRINTINIT_CASH__genmod
          INTERFACE 
            SUBROUTINE GS_PRINTINIT_CASH
            END SUBROUTINE GS_PRINTINIT_CASH
          END INTERFACE 
        END MODULE GS_PRINTINIT_CASH__genmod
