        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE INIT_GSMAIN_S_NDNS__genmod
          INTERFACE 
            SUBROUTINE INIT_GSMAIN_S_NDNS(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE INIT_GSMAIN_S_NDNS
          END INTERFACE 
        END MODULE INIT_GSMAIN_S_NDNS__genmod
