        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:18 2024
        MODULE INIT_BOUND_GU_CYLIDER_PARTICLE_BASE__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUND_GU_CYLIDER_PARTICLE_BASE(KK_OM)
              REAL(KIND=8) :: KK_OM
            END SUBROUTINE INIT_BOUND_GU_CYLIDER_PARTICLE_BASE
          END INTERFACE 
        END MODULE INIT_BOUND_GU_CYLIDER_PARTICLE_BASE__genmod
