        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE INIT_AREA_CASH__genmod
          INTERFACE 
            SUBROUTINE INIT_AREA_CASH(CASH)
              USE PGMOD
              TYPE (TCASH) :: CASH
            END SUBROUTINE INIT_AREA_CASH
          END INTERFACE 
        END MODULE INIT_AREA_CASH__genmod
