        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 05 10:11:09 2025
        MODULE INIT_GEOM__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE INIT_GEOM
          END INTERFACE 
        END MODULE INIT_GEOM__genmod
