        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 12 23:25:44 2024
        MODULE INIT_GEOM_2__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM_2(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE INIT_GEOM_2
          END INTERFACE 
        END MODULE INIT_GEOM_2__genmod
