        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:36 2024
        MODULE INIT_BOUNDLINE_GEOM_ELLIPSE__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDLINE_GEOM_ELLIPSE(IBNDL,NPANEL,X0,Y0,RX&
     &,RY,G0,GAM1,GAM2)
              INTEGER(KIND=4) :: NPANEL
              INTEGER(KIND=4) :: IBNDL
              REAL(KIND=8) :: X0
              REAL(KIND=8) :: Y0
              REAL(KIND=8) :: RX
              REAL(KIND=8) :: RY
              REAL(KIND=8) :: G0
              REAL(KIND=8) :: GAM1
              REAL(KIND=8) :: GAM2
            END SUBROUTINE INIT_BOUNDLINE_GEOM_ELLIPSE
          END INTERFACE 
        END MODULE INIT_BOUNDLINE_GEOM_ELLIPSE__genmod
