        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:30 2024
        MODULE INIT_BOUNDLINE_GU_GENGLOBAL_VAR__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDLINE_GU_GENGLOBAL_VAR(GU,I,IND,VAR)
              USE PGMOD
              TYPE (TBOUNDLINE_GU) ,TARGET :: GU
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: IND
              REAL(KIND=8) :: VAR(GU%BNDL%NPANEL)
            END SUBROUTINE INIT_BOUNDLINE_GU_GENGLOBAL_VAR
          END INTERFACE 
        END MODULE INIT_BOUNDLINE_GU_GENGLOBAL_VAR__genmod
