        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE INITCONST_GREENSOLVE__genmod
          INTERFACE 
            SUBROUTINE INITCONST_GREENSOLVE
            END SUBROUTINE INITCONST_GREENSOLVE
          END INTERFACE 
        END MODULE INITCONST_GREENSOLVE__genmod
