        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 12 23:25:44 2024
        MODULE INIT_GEOM_1_CHEKING__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM_1_CHEKING
            END SUBROUTINE INIT_GEOM_1_CHEKING
          END INTERFACE 
        END MODULE INIT_GEOM_1_CHEKING__genmod
