        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 26 11:02:20 2024
        MODULE INIT_GEOM_2__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM_2(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE INIT_GEOM_2
          END INTERFACE 
        END MODULE INIT_GEOM_2__genmod
