        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE INIT_NEED_CASH_EQ9__genmod
          INTERFACE 
            SUBROUTINE INIT_NEED_CASH_EQ9(MODE,DER,NEED_CASH_B,         &
     &NEED_CASH_A)
              INTEGER(KIND=4) :: MODE
              INTEGER(KIND=4) :: DER
              LOGICAL(KIND=4) :: NEED_CASH_B(0:)
              LOGICAL(KIND=4) :: NEED_CASH_A(0:)
            END SUBROUTINE INIT_NEED_CASH_EQ9
          END INTERFACE 
        END MODULE INIT_NEED_CASH_EQ9__genmod
