        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 26 11:02:20 2024
        MODULE INIT_GEOM__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM
            END SUBROUTINE INIT_GEOM
          END INTERFACE 
        END MODULE INIT_GEOM__genmod
