        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 12 23:25:44 2024
        MODULE INIT_GEOM__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM
            END SUBROUTINE INIT_GEOM
          END INTERFACE 
        END MODULE INIT_GEOM__genmod
