        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE INIT_OMP_BUFFER__genmod
          INTERFACE 
            SUBROUTINE INIT_OMP_BUFFER
            END SUBROUTINE INIT_OMP_BUFFER
          END INTERFACE 
        END MODULE INIT_OMP_BUFFER__genmod
