        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:15 2024
        MODULE INIT_MESH__genmod
          INTERFACE 
            SUBROUTINE INIT_MESH(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE INIT_MESH
          END INTERFACE 
        END MODULE INIT_MESH__genmod
