        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE INIT_GS_TIME__genmod
          INTERFACE 
            SUBROUTINE INIT_GS_TIME
            END SUBROUTINE INIT_GS_TIME
          END INTERFACE 
        END MODULE INIT_GS_TIME__genmod
