        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:41 2024
        MODULE INITCASH_AREA__genmod
          INTERFACE 
            SUBROUTINE INITCASH_AREA(I)
              INTEGER(KIND=4) :: I
            END SUBROUTINE INITCASH_AREA
          END INTERFACE 
        END MODULE INITCASH_AREA__genmod
