        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE INITCASHINTEGRAL__genmod
          INTERFACE 
            SUBROUTINE INITCASHINTEGRAL(C)
              USE PGMOD
              TYPE (TCASHINTEGRAL) :: C
            END SUBROUTINE INITCASHINTEGRAL
          END INTERFACE 
        END MODULE INITCASHINTEGRAL__genmod
