        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE INIT_CPP_J__genmod
          INTERFACE 
            SUBROUTINE INIT_CPP_J
            END SUBROUTINE INIT_CPP_J
          END INTERFACE 
        END MODULE INIT_CPP_J__genmod
