        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE INIT_AB_CASH__genmod
          INTERFACE 
            SUBROUTINE INIT_AB_CASH(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE INIT_AB_CASH
          END INTERFACE 
        END MODULE INIT_AB_CASH__genmod
