        !COMPILER-GENERATED INTERFACE MODULE: Mon Nov 18 13:27:23 2024
        MODULE INIT_GU__genmod
          INTERFACE 
            SUBROUTINE INIT_GU
            END SUBROUTINE INIT_GU
          END INTERFACE 
        END MODULE INIT_GU__genmod
