        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:36 2024
        MODULE INIT_AREAPART_GEOM_REF__genmod
          INTERFACE 
            RECURSIVE SUBROUTINE INIT_AREAPART_GEOM_REF(AREF,AA,BB,CC)
              USE PGMOD
              TYPE (AREAPART) ,TARGET :: AREF
              COMPLEX(KIND=8) :: AA
              COMPLEX(KIND=8) :: BB
              COMPLEX(KIND=8) :: CC
            END SUBROUTINE INIT_AREAPART_GEOM_REF
          END INTERFACE 
        END MODULE INIT_AREAPART_GEOM_REF__genmod
