        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE INIT_MESH_GU__genmod
          INTERFACE 
            SUBROUTINE INIT_MESH_GU
            END SUBROUTINE INIT_MESH_GU
          END INTERFACE 
        END MODULE INIT_MESH_GU__genmod
