        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE INITCASHINTEGRAL__genmod
          INTERFACE 
            SUBROUTINE INITCASHINTEGRAL(C)
              USE PGMOD
              TYPE (TCASHINTEGRAL) :: C
            END SUBROUTINE INITCASHINTEGRAL
          END INTERFACE 
        END MODULE INITCASHINTEGRAL__genmod
