        !COMPILER-GENERATED INTERFACE MODULE: Sun Oct 13 11:14:46 2024
        MODULE INIT_GU__genmod
          INTERFACE 
            SUBROUTINE INIT_GU
            END SUBROUTINE INIT_GU
          END INTERFACE 
        END MODULE INIT_GU__genmod
