        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE INIT_OMP_BUFFER__genmod
          INTERFACE 
            SUBROUTINE INIT_OMP_BUFFER
            END SUBROUTINE INIT_OMP_BUFFER
          END INTERFACE 
        END MODULE INIT_OMP_BUFFER__genmod
