        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE INIT_BB_CASH__genmod
          INTERFACE 
            SUBROUTINE INIT_BB_CASH(IA,KND)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: KND
            END SUBROUTINE INIT_BB_CASH
          END INTERFACE 
        END MODULE INIT_BB_CASH__genmod
