        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 26 11:02:20 2024
        MODULE INIT_GU_1_CHEKING__genmod
          INTERFACE 
            SUBROUTINE INIT_GU_1_CHEKING
            END SUBROUTINE INIT_GU_1_CHEKING
          END INTERFACE 
        END MODULE INIT_GU_1_CHEKING__genmod
