        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 15 13:53:02 2024
        MODULE INIT_MESHVAL__genmod
          INTERFACE 
            SUBROUTINE INIT_MESHVAL(G1)
              INTEGER(KIND=4) :: G1
            END SUBROUTINE INIT_MESHVAL
          END INTERFACE 
        END MODULE INIT_MESHVAL__genmod
