        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:15 2024
        MODULE INIT_GU_2_CHEKING__genmod
          INTERFACE 
            SUBROUTINE INIT_GU_2_CHEKING
            END SUBROUTINE INIT_GU_2_CHEKING
          END INTERFACE 
        END MODULE INIT_GU_2_CHEKING__genmod
