        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE INIT_NEED_CASH2__genmod
          INTERFACE 
            SUBROUTINE INIT_NEED_CASH2(MODE,DER,IS_BA,I,INIT_NEED_CASH_1&
     &,INIT_NEED_CASH_2)
              INTEGER(KIND=4) :: MODE
              INTEGER(KIND=4) :: DER
              INTEGER(KIND=4) :: IS_BA
              INTEGER(KIND=4) :: I
              EXTERNAL INIT_NEED_CASH_1
              EXTERNAL INIT_NEED_CASH_2
            END SUBROUTINE INIT_NEED_CASH2
          END INTERFACE 
        END MODULE INIT_NEED_CASH2__genmod
