        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:34 2024
        MODULE INITCASH__genmod
          INTERFACE 
            SUBROUTINE INITCASH
            END SUBROUTINE INITCASH
          END INTERFACE 
        END MODULE INITCASH__genmod
