        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE INIT_BM_ORDER__genmod
          INTERFACE 
            SUBROUTINE INIT_BM_ORDER
            END SUBROUTINE INIT_BM_ORDER
          END INTERFACE 
        END MODULE INIT_BM_ORDER__genmod
