        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE INIT_BM_ORDER__genmod
          INTERFACE 
            SUBROUTINE INIT_BM_ORDER
            END SUBROUTINE INIT_BM_ORDER
          END INTERFACE 
        END MODULE INIT_BM_ORDER__genmod
