        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE INITCASHINTEGRAL__genmod
          INTERFACE 
            SUBROUTINE INITCASHINTEGRAL(C)
              USE PGMOD
              TYPE (TCASHINTEGRAL) :: C
            END SUBROUTINE INITCASHINTEGRAL
          END INTERFACE 
        END MODULE INITCASHINTEGRAL__genmod
