        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE INIT_BOUND_CASH__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUND_CASH(CASH,NB)
              USE PGMOD
              TYPE (TCASH) ,TARGET :: CASH
              INTEGER(KIND=4) :: NB
            END SUBROUTINE INIT_BOUND_CASH
          END INTERFACE 
        END MODULE INIT_BOUND_CASH__genmod
