        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:28 2024
        MODULE INIT_GEOM_DETALE_BNDL__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM_DETALE_BNDL(IBNDL)
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE INIT_GEOM_DETALE_BNDL
          END INTERFACE 
        END MODULE INIT_GEOM_DETALE_BNDL__genmod
