        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 12 23:25:44 2024
        MODULE INIT_GU_2_CHEKING__genmod
          INTERFACE 
            SUBROUTINE INIT_GU_2_CHEKING
            END SUBROUTINE INIT_GU_2_CHEKING
          END INTERFACE 
        END MODULE INIT_GU_2_CHEKING__genmod
