        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE INIT_MESH_GU2__genmod
          INTERFACE 
            SUBROUTINE INIT_MESH_GU2
            END SUBROUTINE INIT_MESH_GU2
          END INTERFACE 
        END MODULE INIT_MESH_GU2__genmod
