        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 15 13:53:02 2024
        MODULE INIT_GEOM_2_CHEKING__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM_2_CHEKING
            END SUBROUTINE INIT_GEOM_2_CHEKING
          END INTERFACE 
        END MODULE INIT_GEOM_2_CHEKING__genmod
