        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:33 2024
        MODULE INITCASH_AREA__genmod
          INTERFACE 
            SUBROUTINE INITCASH_AREA(I)
              INTEGER(KIND=4) :: I
            END SUBROUTINE INITCASH_AREA
          END INTERFACE 
        END MODULE INITCASH_AREA__genmod
