        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE INIT_GSMAIN_S_NDNS__genmod
          INTERFACE 
            SUBROUTINE INIT_GSMAIN_S_NDNS(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE INIT_GSMAIN_S_NDNS
          END INTERFACE 
        END MODULE INIT_GSMAIN_S_NDNS__genmod
