        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:28 2024
        MODULE INIT_GEOM_DETALE1__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM_DETALE1(IBNDL,I_BEGIN,I_END)
              INTEGER(KIND=4) :: IBNDL
              INTEGER(KIND=4) :: I_BEGIN
              INTEGER(KIND=4) :: I_END
            END SUBROUTINE INIT_GEOM_DETALE1
          END INTERFACE 
        END MODULE INIT_GEOM_DETALE1__genmod
