        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:39 2024
        MODULE INIT_BOUNDLINE_GU_GEN_VAR__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDLINE_GU_GEN_VAR(GU,I,VAR)
              USE PGMOD
              TYPE (TBOUNDLINE_GU) ,TARGET :: GU
              INTEGER(KIND=4) :: I
              REAL(KIND=8) :: VAR(GU%BNDL%NPANEL)
            END SUBROUTINE INIT_BOUNDLINE_GU_GEN_VAR
          END INTERFACE 
        END MODULE INIT_BOUNDLINE_GU_GEN_VAR__genmod
