        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE INIT_MESH_GU__genmod
          INTERFACE 
            SUBROUTINE INIT_MESH_GU
            END SUBROUTINE INIT_MESH_GU
          END INTERFACE 
        END MODULE INIT_MESH_GU__genmod
