        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE INIT_GSMAIN_S_NDNS2__genmod
          INTERFACE 
            SUBROUTINE INIT_GSMAIN_S_NDNS2(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE INIT_GSMAIN_S_NDNS2
          END INTERFACE 
        END MODULE INIT_GSMAIN_S_NDNS2__genmod
