        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE INIT_GS_TIME__genmod
          INTERFACE 
            SUBROUTINE INIT_GS_TIME
            END SUBROUTINE INIT_GS_TIME
          END INTERFACE 
        END MODULE INIT_GS_TIME__genmod
