        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 15 13:53:02 2024
        MODULE INIT_GEOM_1__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM_1(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE INIT_GEOM_1
          END INTERFACE 
        END MODULE INIT_GEOM_1__genmod
