        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:39 2024
        MODULE INIT_BOUNDLINE_GU_GENGLOBAL_CONST__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDLINE_GU_GENGLOBAL_CONST(GU,I,IND,      &
     &VARCONST)
              USE PGMOD
              TYPE (TBOUNDLINE_GU) ,TARGET :: GU
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: IND
              REAL(KIND=8) :: VARCONST
            END SUBROUTINE INIT_BOUNDLINE_GU_GENGLOBAL_CONST
          END INTERFACE 
        END MODULE INIT_BOUNDLINE_GU_GENGLOBAL_CONST__genmod
