        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE INIT_AA_CASH__genmod
          INTERFACE 
            SUBROUTINE INIT_AA_CASH(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE INIT_AA_CASH
          END INTERFACE 
        END MODULE INIT_AA_CASH__genmod
