        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE INIT_BM_ORDER__genmod
          INTERFACE 
            SUBROUTINE INIT_BM_ORDER
            END SUBROUTINE INIT_BM_ORDER
          END INTERFACE 
        END MODULE INIT_BM_ORDER__genmod
