        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:15 2024
        MODULE INIT_GEOM_2__genmod
          INTERFACE 
            SUBROUTINE INIT_GEOM_2(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE INIT_GEOM_2
          END INTERFACE 
        END MODULE INIT_GEOM_2__genmod
