        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:25 2024
        MODULE INITCASH__genmod
          INTERFACE 
            SUBROUTINE INITCASH
            END SUBROUTINE INITCASH
          END INTERFACE 
        END MODULE INITCASH__genmod
