        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE INITCONST_GREENSOLVE__genmod
          INTERFACE 
            SUBROUTINE INITCONST_GREENSOLVE
            END SUBROUTINE INITCONST_GREENSOLVE
          END INTERFACE 
        END MODULE INITCONST_GREENSOLVE__genmod
