        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:41 2024
        MODULE INITCASH__genmod
          INTERFACE 
            SUBROUTINE INITCASH
            END SUBROUTINE INITCASH
          END INTERFACE 
        END MODULE INITCASH__genmod
