        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 26 11:02:20 2024
        MODULE INIT_MESHVAL__genmod
          INTERFACE 
            SUBROUTINE INIT_MESHVAL(G1)
              INTEGER(KIND=4) :: G1
            END SUBROUTINE INIT_MESHVAL
          END INTERFACE 
        END MODULE INIT_MESHVAL__genmod
