        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 26 11:02:20 2024
        MODULE INIT_MESH__genmod
          INTERFACE 
            SUBROUTINE INIT_MESH(G)
              INTEGER(KIND=4) :: G
            END SUBROUTINE INIT_MESH
          END INTERFACE 
        END MODULE INIT_MESH__genmod
