        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE INIT_GSMAIN_S_NDNS_ONE__genmod
          INTERFACE 
            SUBROUTINE INIT_GSMAIN_S_NDNS_ONE(K)
              INTEGER(KIND=4) :: K
            END SUBROUTINE INIT_GSMAIN_S_NDNS_ONE
          END INTERFACE 
        END MODULE INIT_GSMAIN_S_NDNS_ONE__genmod
