        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE INIT_AREAPART_GU__genmod
          INTERFACE 
            SUBROUTINE INIT_AREAPART_GU(IPART,G,K)
              INTEGER(KIND=4) :: IPART
              REAL(KIND=8) :: G(GSAREA%A%PART((IPART))%NTR)
              INTEGER(KIND=4) :: K
            END SUBROUTINE INIT_AREAPART_GU
          END INTERFACE 
        END MODULE INIT_AREAPART_GU__genmod
