        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE INIT_AREA_CASH__genmod
          INTERFACE 
            SUBROUTINE INIT_AREA_CASH(CASH)
              USE PGMOD
              TYPE (TCASH) :: CASH
            END SUBROUTINE INIT_AREA_CASH
          END INTERFACE 
        END MODULE INIT_AREA_CASH__genmod
