        !COMPILER-GENERATED INTERFACE MODULE: Sun Dec 22 15:56:17 2024
        MODULE INIT_GU__genmod
          INTERFACE 
            SUBROUTINE INIT_GU
            END SUBROUTINE INIT_GU
          END INTERFACE 
        END MODULE INIT_GU__genmod
