        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:17 2024
        MODULE INTD_AN45_CORNZ__genmod
          INTERFACE 
            FUNCTION INTD_AN45_CORNZ(Z1,Z2,Z3)
              COMPLEX(KIND=8) :: Z1
              COMPLEX(KIND=8) :: Z2
              COMPLEX(KIND=8) :: Z3
              COMPLEX(KIND=8) :: INTD_AN45_CORNZ
            END FUNCTION INTD_AN45_CORNZ
          END INTERFACE 
        END MODULE INTD_AN45_CORNZ__genmod
