        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:09 2024
        MODULE LOAD_VCL__genmod
          INTERFACE 
            SUBROUTINE LOAD_VCL(MODE)
              INTEGER(KIND=4) :: MODE
            END SUBROUTINE LOAD_VCL
          END INTERFACE 
        END MODULE LOAD_VCL__genmod
