        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE M_TO_SPARSE__genmod
          INTERFACE 
            SUBROUTINE M_TO_SPARSE
            END SUBROUTINE M_TO_SPARSE
          END INTERFACE 
        END MODULE M_TO_SPARSE__genmod
