        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE M_TO_SPARSE__genmod
          INTERFACE 
            SUBROUTINE M_TO_SPARSE
            END SUBROUTINE M_TO_SPARSE
          END INTERFACE 
        END MODULE M_TO_SPARSE__genmod
