        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE M_TO_SPARSE__genmod
          INTERFACE 
            SUBROUTINE M_TO_SPARSE
            END SUBROUTINE M_TO_SPARSE
          END INTERFACE 
        END MODULE M_TO_SPARSE__genmod
