        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 17 10:40:13 2024
        MODULE MAIN_1__genmod
          INTERFACE 
            SUBROUTINE MAIN_1
            END SUBROUTINE MAIN_1
          END INTERFACE 
        END MODULE MAIN_1__genmod
