        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 23 23:31:52 2024
        MODULE MAIN_1__genmod
          INTERFACE 
            SUBROUTINE MAIN_1
            END SUBROUTINE MAIN_1
          END INTERFACE 
        END MODULE MAIN_1__genmod
