        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE MAIN_BLOCK_SPARSE__genmod
          INTERFACE 
            SUBROUTINE MAIN_BLOCK_SPARSE
            END SUBROUTINE MAIN_BLOCK_SPARSE
          END INTERFACE 
        END MODULE MAIN_BLOCK_SPARSE__genmod
