        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 12 23:25:44 2024
        MODULE MAIN_2__genmod
          INTERFACE 
            SUBROUTINE MAIN_2
            END SUBROUTINE MAIN_2
          END INTERFACE 
        END MODULE MAIN_2__genmod
