        !COMPILER-GENERATED INTERFACE MODULE: Sun Dec 01 15:01:22 2024
        MODULE MAIN_1__genmod
          INTERFACE 
            SUBROUTINE MAIN_1
            END SUBROUTINE MAIN_1
          END INTERFACE 
        END MODULE MAIN_1__genmod
