        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:41 2024
        MODULE MATRIX_RESORT__genmod
          INTERFACE 
            SUBROUTINE MATRIX_RESORT
            END SUBROUTINE MATRIX_RESORT
          END INTERFACE 
        END MODULE MATRIX_RESORT__genmod
