        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:33 2024
        MODULE MATRIX_RESORT__genmod
          INTERFACE 
            SUBROUTINE MATRIX_RESORT
            END SUBROUTINE MATRIX_RESORT
          END INTERFACE 
        END MODULE MATRIX_RESORT__genmod
