        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE MATRIX_RESORT__genmod
          INTERFACE 
            SUBROUTINE MATRIX_RESORT
            END SUBROUTINE MATRIX_RESORT
          END INTERFACE 
        END MODULE MATRIX_RESORT__genmod
