        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE NULL_GEOM_DETALE__genmod
          INTERFACE 
            SUBROUTINE NULL_GEOM_DETALE(IB,IGD)
              INTEGER(KIND=4) :: IB
              INTEGER(KIND=4) :: IGD
            END SUBROUTINE NULL_GEOM_DETALE
          END INTERFACE 
        END MODULE NULL_GEOM_DETALE__genmod
