        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE NULL_MATRIX__genmod
          INTERFACE 
            SUBROUTINE NULL_MATRIX
            END SUBROUTINE NULL_MATRIX
          END INTERFACE 
        END MODULE NULL_MATRIX__genmod
