        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE NULLBOUND__genmod
          INTERFACE 
            SUBROUTINE NULLBOUND(IBND)
              INTEGER(KIND=4) :: IBND
            END SUBROUTINE NULLBOUND
          END INTERFACE 
        END MODULE NULLBOUND__genmod
