        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE NULL_AREAPART__genmod
          INTERFACE 
            SUBROUTINE NULL_AREAPART(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE NULL_AREAPART
          END INTERFACE 
        END MODULE NULL_AREAPART__genmod
