        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE NULLBOUND__genmod
          INTERFACE 
            SUBROUTINE NULLBOUND(IBND)
              INTEGER(KIND=4) :: IBND
            END SUBROUTINE NULLBOUND
          END INTERFACE 
        END MODULE NULLBOUND__genmod
