        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE NULLBOUNDLINE__genmod
          INTERFACE 
            SUBROUTINE NULLBOUNDLINE(IBNDL)
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE NULLBOUNDLINE
          END INTERFACE 
        END MODULE NULLBOUNDLINE__genmod
