        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE NULLAREA__genmod
          INTERFACE 
            SUBROUTINE NULLAREA(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE NULLAREA
          END INTERFACE 
        END MODULE NULLAREA__genmod
