        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE NULLBOUNDLINE__genmod
          INTERFACE 
            SUBROUTINE NULLBOUNDLINE(IBNDL)
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE NULLBOUNDLINE
          END INTERFACE 
        END MODULE NULLBOUNDLINE__genmod
