        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE NULL_AREAPART__genmod
          INTERFACE 
            SUBROUTINE NULL_AREAPART(IA)
              INTEGER(KIND=4) :: IA
            END SUBROUTINE NULL_AREAPART
          END INTERFACE 
        END MODULE NULL_AREAPART__genmod
