        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE NULLBOUND__genmod
          INTERFACE 
            SUBROUTINE NULLBOUND(IBND)
              INTEGER(KIND=4) :: IBND
            END SUBROUTINE NULLBOUND
          END INTERFACE 
        END MODULE NULLBOUND__genmod
