        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE NULL_MATRIX__genmod
          INTERFACE 
            SUBROUTINE NULL_MATRIX
            END SUBROUTINE NULL_MATRIX
          END INTERFACE 
        END MODULE NULL_MATRIX__genmod
