        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE NULLBOUNDLINE__genmod
          INTERFACE 
            SUBROUTINE NULLBOUNDLINE(IBNDL)
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE NULLBOUNDLINE
          END INTERFACE 
        END MODULE NULLBOUNDLINE__genmod
