        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE NULLBOUNDLINE2__genmod
          INTERFACE 
            SUBROUTINE NULLBOUNDLINE2(IBNDL)
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE NULLBOUNDLINE2
          END INTERFACE 
        END MODULE NULLBOUNDLINE2__genmod
