        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE PG_ALLOCATE_AREAPART_GEOM_N__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AREAPART_GEOM_N(IN)
              INTEGER(KIND=4) :: IN
            END SUBROUTINE PG_ALLOCATE_AREAPART_GEOM_N
          END INTERFACE 
        END MODULE PG_ALLOCATE_AREAPART_GEOM_N__genmod
