        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE PG_ALLOCATE_AREA__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AREA(INPART)
              INTEGER(KIND=4) :: INPART
            END SUBROUTINE PG_ALLOCATE_AREA
          END INTERFACE 
        END MODULE PG_ALLOCATE_AREA__genmod
