        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE PG_ALLOCATE_AND_SET_GA2_BASE__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AND_SET_GA2_BASE(GA,N)
              USE PGMOD
              TYPE (TBOUNLINEFUNCAPPROX) :: GA
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_ALLOCATE_AND_SET_GA2_BASE
          END INTERFACE 
        END MODULE PG_ALLOCATE_AND_SET_GA2_BASE__genmod
