        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:28 2024
        MODULE PG_ADD_BOUNDLINE_GEOMLINEDS2__genmod
          INTERFACE 
            SUBROUTINE PG_ADD_BOUNDLINE_GEOMLINEDS2(IBNDL,DS1,DS2,X1,Y1,&
     &X2,Y2)
              INTEGER(KIND=4) :: IBNDL
              REAL(KIND=8) :: DS1
              REAL(KIND=8) :: DS2
              REAL(KIND=8) :: X1
              REAL(KIND=8) :: Y1
              REAL(KIND=8) :: X2
              REAL(KIND=8) :: Y2
            END SUBROUTINE PG_ADD_BOUNDLINE_GEOMLINEDS2
          END INTERFACE 
        END MODULE PG_ADD_BOUNDLINE_GEOMLINEDS2__genmod
