        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE PG_ALLOCATE_AND_SET_GA2__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AND_SET_GA2(IGA,N)
              INTEGER(KIND=4) :: IGA
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_ALLOCATE_AND_SET_GA2
          END INTERFACE 
        END MODULE PG_ALLOCATE_AND_SET_GA2__genmod
