        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE PG_ALLOCATE_AREA_GU__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AREA_GU
            END SUBROUTINE PG_ALLOCATE_AREA_GU
          END INTERFACE 
        END MODULE PG_ALLOCATE_AREA_GU__genmod
