        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:17 2024
        MODULE PG_ALLOCATE_BOUNDLINES__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_BOUNDLINES(NLINE)
              INTEGER(KIND=4) :: NLINE
            END SUBROUTINE PG_ALLOCATE_BOUNDLINES
          END INTERFACE 
        END MODULE PG_ALLOCATE_BOUNDLINES__genmod
