        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE PG_ALLOCATE_BOUNDLINES__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_BOUNDLINES(NLINE)
              INTEGER(KIND=4) :: NLINE
            END SUBROUTINE PG_ALLOCATE_BOUNDLINES
          END INTERFACE 
        END MODULE PG_ALLOCATE_BOUNDLINES__genmod
