        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE PG_ALLOCATE_DOMAINS__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_DOMAINS(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_ALLOCATE_DOMAINS
          END INTERFACE 
        END MODULE PG_ALLOCATE_DOMAINS__genmod
