        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:29 2024
        MODULE PG_AREAGEOM_POSTPROCESSOR__genmod
          INTERFACE 
            SUBROUTINE PG_AREAGEOM_POSTPROCESSOR
            END SUBROUTINE PG_AREAGEOM_POSTPROCESSOR
          END INTERFACE 
        END MODULE PG_AREAGEOM_POSTPROCESSOR__genmod
