        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE PG_ALLOCATE_BOUNDLINES__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_BOUNDLINES(NLINE)
              INTEGER(KIND=4) :: NLINE
            END SUBROUTINE PG_ALLOCATE_BOUNDLINES
          END INTERFACE 
        END MODULE PG_ALLOCATE_BOUNDLINES__genmod
