        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE PG_ALLOCATE_BOUND_GU2__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_BOUND_GU2
            END SUBROUTINE PG_ALLOCATE_BOUND_GU2
          END INTERFACE 
        END MODULE PG_ALLOCATE_BOUND_GU2__genmod
