        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE PG_ALLOCATE_AREA__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AREA(INPART)
              INTEGER(KIND=4) :: INPART
            END SUBROUTINE PG_ALLOCATE_AREA
          END INTERFACE 
        END MODULE PG_ALLOCATE_AREA__genmod
