        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE PG_ALLOCATE_AND_SET_GA2_BASE__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_AND_SET_GA2_BASE(GA,N)
              USE PGMOD
              TYPE (TBOUNLINEFUNCAPPROX) :: GA
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_ALLOCATE_AND_SET_GA2_BASE
          END INTERFACE 
        END MODULE PG_ALLOCATE_AND_SET_GA2_BASE__genmod
