        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:29 2024
        MODULE PG_ADD_BOUNDLINE_GEOM__genmod
          INTERFACE 
            SUBROUTINE PG_ADD_BOUNDLINE_GEOM(IBNDL,NPANEL,X,Y)
              INTEGER(KIND=4) :: NPANEL
              INTEGER(KIND=4) :: IBNDL
              REAL(KIND=8) :: X(NPANEL+1)
              REAL(KIND=8) :: Y(NPANEL+1)
            END SUBROUTINE PG_ADD_BOUNDLINE_GEOM
          END INTERFACE 
        END MODULE PG_ADD_BOUNDLINE_GEOM__genmod
