        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:11 2024
        MODULE PG_AREAGEOM_POSTPROCESSOR__genmod
          INTERFACE 
            SUBROUTINE PG_AREAGEOM_POSTPROCESSOR
            END SUBROUTINE PG_AREAGEOM_POSTPROCESSOR
          END INTERFACE 
        END MODULE PG_AREAGEOM_POSTPROCESSOR__genmod
