        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE PG_ALLOCATE_BOUNDLINE_GU_ADD2__genmod
          INTERFACE 
            SUBROUTINE PG_ALLOCATE_BOUNDLINE_GU_ADD2(CP_LINE)
              LOGICAL(KIND=4) :: CP_LINE
            END SUBROUTINE PG_ALLOCATE_BOUNDLINE_GU_ADD2
          END INTERFACE 
        END MODULE PG_ALLOCATE_BOUNDLINE_GU_ADD2__genmod
