        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE PG_BIND_DOMAIN__genmod
          INTERFACE 
            SUBROUTINE PG_BIND_DOMAIN(K)
              INTEGER(KIND=4) :: K
            END SUBROUTINE PG_BIND_DOMAIN
          END INTERFACE 
        END MODULE PG_BIND_DOMAIN__genmod
