        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE PG_BIND_DOMAIN__genmod
          INTERFACE 
            SUBROUTINE PG_BIND_DOMAIN(K)
              INTEGER(KIND=4) :: K
            END SUBROUTINE PG_BIND_DOMAIN
          END INTERFACE 
        END MODULE PG_BIND_DOMAIN__genmod
