        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE PG_BIND_BOUND__genmod
          INTERFACE 
            SUBROUTINE PG_BIND_BOUND(K)
              INTEGER(KIND=4) :: K
            END SUBROUTINE PG_BIND_BOUND
          END INTERFACE 
        END MODULE PG_BIND_BOUND__genmod
