        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:16 2024
        MODULE PG_CLOSING_PSICONST__genmod
          INTERFACE 
            SUBROUTINE PG_CLOSING_PSICONST(IBND)
              INTEGER(KIND=4) :: IBND
            END SUBROUTINE PG_CLOSING_PSICONST
          END INTERFACE 
        END MODULE PG_CLOSING_PSICONST__genmod
