        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:11 2024
        MODULE PG_COPY_BOUNDLINE__genmod
          INTERFACE 
            SUBROUTINE PG_COPY_BOUNDLINE(IBNDL,IP2,IA2,IBND2,IBNDL2)
              INTEGER(KIND=4) :: IBNDL
              INTEGER(KIND=4) :: IP2
              INTEGER(KIND=4) :: IA2
              INTEGER(KIND=4) :: IBND2
              INTEGER(KIND=4) :: IBNDL2
            END SUBROUTINE PG_COPY_BOUNDLINE
          END INTERFACE 
        END MODULE PG_COPY_BOUNDLINE__genmod
