        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:16 2024
        MODULE PG_CLOSING_PSICONST_ARR2_DP__genmod
          INTERFACE 
            SUBROUTINE PG_CLOSING_PSICONST_ARR2_DP(IA,IBND,IBNDL,N,     &
     &IA_ADD,DP)
              INTEGER(KIND=4) :: N
              INTEGER(KIND=4) :: IA(N)
              INTEGER(KIND=4) :: IBND(N)
              INTEGER(KIND=4) :: IBNDL(N)
              INTEGER(KIND=4) :: IA_ADD
              REAL(KIND=8) :: DP
            END SUBROUTINE PG_CLOSING_PSICONST_ARR2_DP
          END INTERFACE 
        END MODULE PG_CLOSING_PSICONST_ARR2_DP__genmod
