        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:16 2024
        MODULE PG_CLOSING_PSICONST2__genmod
          INTERFACE 
            SUBROUTINE PG_CLOSING_PSICONST2(IBND,I1,I2)
              INTEGER(KIND=4) :: IBND
              INTEGER(KIND=4) :: I1
              INTEGER(KIND=4) :: I2
            END SUBROUTINE PG_CLOSING_PSICONST2
          END INTERFACE 
        END MODULE PG_CLOSING_PSICONST2__genmod
