        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:31 2024
        MODULE PG_CLOSING_MATRIX_DARCIDARCI__genmod
          INTERFACE 
            SUBROUTINE PG_CLOSING_MATRIX_DARCIDARCI(IA1,IBND1,IBNDL1,IA2&
     &,IBND2,IBNDL2,KKR)
              INTEGER(KIND=4) :: IA1
              INTEGER(KIND=4) :: IBND1
              INTEGER(KIND=4) :: IBNDL1
              INTEGER(KIND=4) :: IA2
              INTEGER(KIND=4) :: IBND2
              INTEGER(KIND=4) :: IBNDL2
              REAL(KIND=8) :: KKR
            END SUBROUTINE PG_CLOSING_MATRIX_DARCIDARCI
          END INTERFACE 
        END MODULE PG_CLOSING_MATRIX_DARCIDARCI__genmod
