        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:16 2024
        MODULE PG_CLOSING_PSICONST_ARR2__genmod
          INTERFACE 
            SUBROUTINE PG_CLOSING_PSICONST_ARR2(IA,IBND,IBNDL,N,IA_ADD)
              INTEGER(KIND=4) :: N
              INTEGER(KIND=4) :: IA(N)
              INTEGER(KIND=4) :: IBND(N)
              INTEGER(KIND=4) :: IBNDL(N)
              INTEGER(KIND=4) :: IA_ADD
            END SUBROUTINE PG_CLOSING_PSICONST_ARR2
          END INTERFACE 
        END MODULE PG_CLOSING_PSICONST_ARR2__genmod
