        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:40 2024
        MODULE PG_CLOSING_MATRIX_BRI__genmod
          INTERFACE 
            SUBROUTINE PG_CLOSING_MATRIX_BRI(IA1,IBND1,IBNDL1,IA2,IBND2,&
     &IBNDL2,S_DARCI)
              INTEGER(KIND=4) :: IA1
              INTEGER(KIND=4) :: IBND1
              INTEGER(KIND=4) :: IBNDL1
              INTEGER(KIND=4) :: IA2
              INTEGER(KIND=4) :: IBND2
              INTEGER(KIND=4) :: IBNDL2
              REAL(KIND=8) :: S_DARCI
            END SUBROUTINE PG_CLOSING_MATRIX_BRI
          END INTERFACE 
        END MODULE PG_CLOSING_MATRIX_BRI__genmod
