        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:16 2024
        MODULE PG_CLOSING_PSICONST_LINE__genmod
          INTERFACE 
            SUBROUTINE PG_CLOSING_PSICONST_LINE(IBND,IBNDL)
              INTEGER(KIND=4) :: IBND
              INTEGER(KIND=4) :: IBNDL
            END SUBROUTINE PG_CLOSING_PSICONST_LINE
          END INTERFACE 
        END MODULE PG_CLOSING_PSICONST_LINE__genmod
