        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:11 2024
        MODULE PG_COPY_BOUNDLINE_DXDY_ROTATE__genmod
          INTERFACE 
            SUBROUTINE PG_COPY_BOUNDLINE_DXDY_ROTATE(IBNDL,IP2,IA2,IBND2&
     &,IBNDL2,DX,DY,ANGLE,XR,YR)
              INTEGER(KIND=4) :: IBNDL
              INTEGER(KIND=4) :: IP2
              INTEGER(KIND=4) :: IA2
              INTEGER(KIND=4) :: IBND2
              INTEGER(KIND=4) :: IBNDL2
              REAL(KIND=8) :: DX
              REAL(KIND=8) :: DY
              REAL(KIND=8) :: ANGLE
              REAL(KIND=8) :: XR
              REAL(KIND=8) :: YR
            END SUBROUTINE PG_COPY_BOUNDLINE_DXDY_ROTATE
          END INTERFACE 
        END MODULE PG_COPY_BOUNDLINE_DXDY_ROTATE__genmod
