        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE PG_DEALLOCATE_MEM__genmod
          INTERFACE 
            SUBROUTINE PG_DEALLOCATE_MEM
            END SUBROUTINE PG_DEALLOCATE_MEM
          END INTERFACE 
        END MODULE PG_DEALLOCATE_MEM__genmod
