        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:35 2024
        MODULE PG_GET_FUN_XY_GRADIENT__genmod
          INTERFACE 
            SUBROUTINE PG_GET_FUN_XY_GRADIENT(XX,YY,NF,MODE,FF)
              REAL(KIND=8) :: XX
              REAL(KIND=8) :: YY
              INTEGER(KIND=4) :: NF
              INTEGER(KIND=4) :: MODE
              REAL(KIND=8) :: FF(2)
            END SUBROUTINE PG_GET_FUN_XY_GRADIENT
          END INTERFACE 
        END MODULE PG_GET_FUN_XY_GRADIENT__genmod
