        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:14 2024
        MODULE PG_GET_NEXT_CONSTIND__genmod
          INTERFACE 
            FUNCTION PG_GET_NEXT_CONSTIND
              INTEGER(KIND=4) :: PG_GET_NEXT_CONSTIND
            END FUNCTION PG_GET_NEXT_CONSTIND
          END INTERFACE 
        END MODULE PG_GET_NEXT_CONSTIND__genmod
