        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:25 2024
        MODULE PG_GET_MATRIX_FINF__genmod
          INTERFACE 
            SUBROUTINE PG_GET_MATRIX_FINF(FUNC_INF)
              REAL(KIND=8) :: FUNC_INF
              EXTERNAL FUNC_INF
            END SUBROUTINE PG_GET_MATRIX_FINF
          END INTERFACE 
        END MODULE PG_GET_MATRIX_FINF__genmod
