        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE PG_GET_NEXT_CONSTIND__genmod
          INTERFACE 
            FUNCTION PG_GET_NEXT_CONSTIND
              INTEGER(KIND=4) :: PG_GET_NEXT_CONSTIND
            END FUNCTION PG_GET_NEXT_CONSTIND
          END INTERFACE 
        END MODULE PG_GET_NEXT_CONSTIND__genmod
