        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:41 2024
        MODULE PG_GET_MATRIX__genmod
          INTERFACE 
            SUBROUTINE PG_GET_MATRIX
            END SUBROUTINE PG_GET_MATRIX
          END INTERFACE 
        END MODULE PG_GET_MATRIX__genmod
