        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:25 2024
        MODULE PG_GET_MATRIX__genmod
          INTERFACE 
            SUBROUTINE PG_GET_MATRIX
            END SUBROUTINE PG_GET_MATRIX
          END INTERFACE 
        END MODULE PG_GET_MATRIX__genmod
