        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:35 2024
        MODULE PG_GET_PSIOML__genmod
          INTERFACE 
            SUBROUTINE PG_GET_PSIOML
            END SUBROUTINE PG_GET_PSIOML
          END INTERFACE 
        END MODULE PG_GET_PSIOML__genmod
