        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:22 2024
        MODULE PG_GET_PSIOML__genmod
          INTERFACE 
            SUBROUTINE PG_GET_PSIOML
            END SUBROUTINE PG_GET_PSIOML
          END INTERFACE 
        END MODULE PG_GET_PSIOML__genmod
