        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:34 2024
        MODULE PG_GET_MATRIX__genmod
          INTERFACE 
            SUBROUTINE PG_GET_MATRIX
            END SUBROUTINE PG_GET_MATRIX
          END INTERFACE 
        END MODULE PG_GET_MATRIX__genmod
