        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:39 2024
        MODULE PG_INIT_BOUNDLINE_GU_STOKS_DARCY__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_STOKS_DARCY(IA1,IBND1,IBNDL1&
     &,IA2,IBND2,IBNDL2,S_DARCY,ALF_DARCY,BET_DARCY)
              INTEGER(KIND=4) :: IA1
              INTEGER(KIND=4) :: IBND1
              INTEGER(KIND=4) :: IBNDL1
              INTEGER(KIND=4) :: IA2
              INTEGER(KIND=4) :: IBND2
              INTEGER(KIND=4) :: IBNDL2
              REAL(KIND=8) :: S_DARCY
              REAL(KIND=8) :: ALF_DARCY
              REAL(KIND=8) :: BET_DARCY
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_STOKS_DARCY
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_STOKS_DARCY__genmod
