        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:30 2024
        MODULE PG_INIT_BOUNDLINE_GU_VAL_CONST__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_VAL_CONST(IGU,BNDF,BNDVAL)
              INTEGER(KIND=4) :: IGU
              INTEGER(KIND=4) :: BNDF
              REAL(KIND=8) :: BNDVAL
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_VAL_CONST
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_VAL_CONST__genmod
