        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:18 2024
        MODULE PG_INIT_BOUND_GU_EMPTY__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUND_GU_EMPTY
            END SUBROUTINE PG_INIT_BOUND_GU_EMPTY
          END INTERFACE 
        END MODULE PG_INIT_BOUND_GU_EMPTY__genmod
