        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:18 2024
        MODULE PG_INIT_BOUNDLINE_GU_GEN_VAR__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_GEN_VAR(IGU,I,VAR)
              INTEGER(KIND=4) :: IGU
              INTEGER(KIND=4) :: I
              REAL(KIND=8) :: VAR(*)
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_GEN_VAR
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_GEN_VAR__genmod
