        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:25 2024
        MODULE PG_INITCASH_AREA__genmod
          INTERFACE 
            SUBROUTINE PG_INITCASH_AREA
            END SUBROUTINE PG_INITCASH_AREA
          END INTERFACE 
        END MODULE PG_INITCASH_AREA__genmod
