        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE PG_INIT_AREAPART_GEOM_TR__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_AREAPART_GEOM_TR(TR)
              INTEGER(KIND=4) :: TR(GSAREAPART%NPE*GSAREAPART%NTR)
            END SUBROUTINE PG_INIT_AREAPART_GEOM_TR
          END INTERFACE 
        END MODULE PG_INIT_AREAPART_GEOM_TR__genmod
