        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:18 2024
        MODULE PG_INIT_BOUNDLINE_GU_SUBDOMAIN_CONTINUITY__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_SUBDOMAIN_CONTINUITY(IA1,   &
     &IBND1,IBNDL1,IA2,IBND2,IBNDL2)
              INTEGER(KIND=4) :: IA1
              INTEGER(KIND=4) :: IBND1
              INTEGER(KIND=4) :: IBNDL1
              INTEGER(KIND=4) :: IA2
              INTEGER(KIND=4) :: IBND2
              INTEGER(KIND=4) :: IBNDL2
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_SUBDOMAIN_CONTINUITY
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_SUBDOMAIN_CONTINUITY__genmod
