        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:39 2024
        MODULE PG_INIT_BOUND_GU_EMPTY__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUND_GU_EMPTY
            END SUBROUTINE PG_INIT_BOUND_GU_EMPTY
          END INTERFACE 
        END MODULE PG_INIT_BOUND_GU_EMPTY__genmod
