        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:11 2024
        MODULE PG_INIT_AREAPART_GEOM_REF_DXDY_ROTATE__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_AREAPART_GEOM_REF_DXDY_ROTATE(IP,IA,IPART&
     &,DX,DY,ANGLE,XR,YR)
              INTEGER(KIND=4) :: IP
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IPART
              REAL(KIND=8) :: DX
              REAL(KIND=8) :: DY
              REAL(KIND=8) :: ANGLE
              REAL(KIND=8) :: XR
              REAL(KIND=8) :: YR
            END SUBROUTINE PG_INIT_AREAPART_GEOM_REF_DXDY_ROTATE
          END INTERFACE 
        END MODULE PG_INIT_AREAPART_GEOM_REF_DXDY_ROTATE__genmod
