        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:29 2024
        MODULE PG_INIT_SUBDMAIN_BLOCK_ORDER__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_SUBDMAIN_BLOCK_ORDER(GET_FIRST_BOUND)
              LOGICAL(KIND=4) :: GET_FIRST_BOUND
              EXTERNAL GET_FIRST_BOUND
            END SUBROUTINE PG_INIT_SUBDMAIN_BLOCK_ORDER
          END INTERFACE 
        END MODULE PG_INIT_SUBDMAIN_BLOCK_ORDER__genmod
