        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE PG_INIT_AREA_GU__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_AREA_GU(G,K)
              REAL(KIND=8) :: G(GSAREA%A%NTR)
              INTEGER(KIND=4) :: K
            END SUBROUTINE PG_INIT_AREA_GU
          END INTERFACE 
        END MODULE PG_INIT_AREA_GU__genmod
