        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:18 2024
        MODULE PG_INIT_BOUNDLINE_GU_EMPTY_ONE__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_EMPTY_ONE(IGU)
              INTEGER(KIND=4) :: IGU
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_EMPTY_ONE
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_EMPTY_ONE__genmod
