        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:30 2024
        MODULE PG_INIT_BOUND_GU_VAL__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUND_GU_VAL(IGU,BNDF,BNDVAL)
              INTEGER(KIND=4) :: IGU
              INTEGER(KIND=4) :: BNDF
              REAL(KIND=8) :: BNDVAL(GSBND%NPANEL)
            END SUBROUTINE PG_INIT_BOUND_GU_VAL
          END INTERFACE 
        END MODULE PG_INIT_BOUND_GU_VAL__genmod
