        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:30 2024
        MODULE PG_INIT_BOUNDLINE_GU_PERIODIC_PERENOS__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_PERIODIC_PERENOS(IA1,IBND1, &
     &IBNDL1,IA2,IBND2,IBNDL2,IS_DIRECT,KC)
              INTEGER(KIND=4) :: IA1
              INTEGER(KIND=4) :: IBND1
              INTEGER(KIND=4) :: IBNDL1
              INTEGER(KIND=4) :: IA2
              INTEGER(KIND=4) :: IBND2
              INTEGER(KIND=4) :: IBNDL2
              LOGICAL(KIND=4) :: IS_DIRECT
              REAL(KIND=8) :: KC
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_PERIODIC_PERENOS
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_PERIODIC_PERENOS__genmod
