        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:41 2024
        MODULE PG_INIT_NEED_CASH_FOR_FUNC__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_NEED_CASH_FOR_FUNC(MODE,DER,IS_BA,       &
     &CLEAR_NEED_CASH)
              INTEGER(KIND=4) :: MODE
              INTEGER(KIND=4) :: DER
              INTEGER(KIND=4) :: IS_BA
              LOGICAL(KIND=4) :: CLEAR_NEED_CASH
            END SUBROUTINE PG_INIT_NEED_CASH_FOR_FUNC
          END INTERFACE 
        END MODULE PG_INIT_NEED_CASH_FOR_FUNC__genmod
