        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:41 2024
        MODULE PG_INITCASH_AREA__genmod
          INTERFACE 
            SUBROUTINE PG_INITCASH_AREA
            END SUBROUTINE PG_INITCASH_AREA
          END INTERFACE 
        END MODULE PG_INITCASH_AREA__genmod
