        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:18 2024
        MODULE PG_INIT_BOUNDLINE_GU_SLIP2__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_SLIP2(IGU,SLIP_K)
              INTEGER(KIND=4) :: IGU
              REAL(KIND=8) :: SLIP_K
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_SLIP2
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_SLIP2__genmod
