        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:41 2024
        MODULE PG_INITCASH_AREA_AR__genmod
          INTERFACE 
            SUBROUTINE PG_INITCASH_AREA_AR(IA1,IA2)
              INTEGER(KIND=4) :: IA1
              INTEGER(KIND=4) :: IA2
            END SUBROUTINE PG_INITCASH_AREA_AR
          END INTERFACE 
        END MODULE PG_INITCASH_AREA_AR__genmod
