        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:18 2024
        MODULE PG_INIT_BOUNDLINE_GU_GENGLOBAL_VAR__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_GENGLOBAL_VAR(IGU,I,IND,VAR)
              INTEGER(KIND=4) :: IGU
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: IND
              REAL(KIND=8) :: VAR(*)
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_GENGLOBAL_VAR
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_GENGLOBAL_VAR__genmod
