        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:30 2024
        MODULE PG_INIT_GU_MULTIAREA2__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_GU_MULTIAREA2(SET_GU_EXTERNAL)
              EXTERNAL SET_GU_EXTERNAL
            END SUBROUTINE PG_INIT_GU_MULTIAREA2
          END INTERFACE 
        END MODULE PG_INIT_GU_MULTIAREA2__genmod
