        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:30 2024
        MODULE PG_INIT_BOUNDLINE_GU_STOKS_BRINKMAN__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_STOKS_BRINKMAN(IA1,IBND1,   &
     &IBNDL1,IA2,IBND2,IBNDL2,BET,DELT,K_BRI,MU_BRI)
              INTEGER(KIND=4) :: IA1
              INTEGER(KIND=4) :: IBND1
              INTEGER(KIND=4) :: IBNDL1
              INTEGER(KIND=4) :: IA2
              INTEGER(KIND=4) :: IBND2
              INTEGER(KIND=4) :: IBNDL2
              REAL(KIND=8) :: BET
              REAL(KIND=8) :: DELT
              REAL(KIND=8) :: K_BRI
              REAL(KIND=8) :: MU_BRI
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_STOKS_BRINKMAN
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_STOKS_BRINKMAN__genmod
