        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:39 2024
        MODULE PG_INIT_BOUNDLINE_GU_EMPTY_ONE__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_EMPTY_ONE(IGU)
              INTEGER(KIND=4) :: IGU
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_EMPTY_ONE
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_EMPTY_ONE__genmod
