        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:39 2024
        MODULE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_SLIP__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_SLIP(K_SLIP)
              REAL(KIND=8) :: K_SLIP
            END SUBROUTINE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_SLIP
          END INTERFACE 
        END MODULE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_SLIP__genmod
