        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:30 2024
        MODULE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_ALL2__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_ALL2(MODE,PARAM&
     &)
              INTEGER(KIND=4) :: MODE
              REAL(KIND=8) :: PARAM
            END SUBROUTINE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_ALL2
          END INTERFACE 
        END MODULE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_ALL2__genmod
