        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:30 2024
        MODULE PG_INIT_BOUNDLINE_GU_CONSTVAL__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_CONSTVAL(IGU,BNDF,CONSTVALI)
              INTEGER(KIND=4) :: IGU
              INTEGER(KIND=4) :: BNDF
              INTEGER(KIND=4) :: CONSTVALI
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_CONSTVAL
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_CONSTVAL__genmod
