        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:29 2024
        MODULE PG_INIT_SUBDMAIN_CONNECTIVITY__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_SUBDMAIN_CONNECTIVITY(                   &
     &TEST_POINT_COORDINATES)
              LOGICAL(KIND=4) :: TEST_POINT_COORDINATES
            END SUBROUTINE PG_INIT_SUBDMAIN_CONNECTIVITY
          END INTERFACE 
        END MODULE PG_INIT_SUBDMAIN_CONNECTIVITY__genmod
