        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:28 2024
        MODULE PG_INIT_BOUNDLINE_GEOMPOLYLINEDS__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GEOMPOLYLINEDS(IBNDL,DS,X,Y,N)
              INTEGER(KIND=4) :: N
              INTEGER(KIND=4) :: IBNDL
              REAL(KIND=8) :: DS
              REAL(KIND=8) :: X(N+1)
              REAL(KIND=8) :: Y(N+1)
            END SUBROUTINE PG_INIT_BOUNDLINE_GEOMPOLYLINEDS
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GEOMPOLYLINEDS__genmod
