        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:18 2024
        MODULE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_SLIP__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_SLIP(K_SLIP)
              REAL(KIND=8) :: K_SLIP
            END SUBROUTINE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_SLIP
          END INTERFACE 
        END MODULE PG_INIT_BOUND_GU_CYLIDER_PARTICLE_SLIP__genmod
