        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:18 2024
        MODULE PG_INIT_BOUNDLINE_GU_SYMMETR__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_SYMMETR(IGU,BNDF,IS_DIRECT, &
     &IA,IBND,IBNDL,C0_,C1_)
              INTEGER(KIND=4) :: IGU
              INTEGER(KIND=4) :: BNDF
              LOGICAL(KIND=4) :: IS_DIRECT
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: IBND
              INTEGER(KIND=4) :: IBNDL
              REAL(KIND=8) :: C0_
              REAL(KIND=8) :: C1_
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_SYMMETR
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_SYMMETR__genmod
