        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:30 2024
        MODULE PG_INIT_BOUNDLINE_GU_EMPTY__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_EMPTY
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_EMPTY
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_EMPTY__genmod
