        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE PG_INIT_AREA_GU_OSS__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_AREA_GU_OSS
            END SUBROUTINE PG_INIT_AREA_GU_OSS
          END INTERFACE 
        END MODULE PG_INIT_AREA_GU_OSS__genmod
