        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:30 2024
        MODULE PG_INIT_BOUNDLINE_GU_DARCY_DARCY__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_BOUNDLINE_GU_DARCY_DARCY(IA1,IBND1,IBNDL1&
     &,IA2,IBND2,IBNDL2,K1_DIV_K2)
              INTEGER(KIND=4) :: IA1
              INTEGER(KIND=4) :: IBND1
              INTEGER(KIND=4) :: IBNDL1
              INTEGER(KIND=4) :: IA2
              INTEGER(KIND=4) :: IBND2
              INTEGER(KIND=4) :: IBNDL2
              REAL(KIND=8) :: K1_DIV_K2
            END SUBROUTINE PG_INIT_BOUNDLINE_GU_DARCY_DARCY
          END INTERFACE 
        END MODULE PG_INIT_BOUNDLINE_GU_DARCY_DARCY__genmod
