        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:30 2024
        MODULE PG_INIT_GU_MULTIAREA__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_GU_MULTIAREA(SET_GU_INTERNAL,            &
     &SET_GU_EXTERNAL)
              EXTERNAL SET_GU_INTERNAL
              EXTERNAL SET_GU_EXTERNAL
            END SUBROUTINE PG_INIT_GU_MULTIAREA
          END INTERFACE 
        END MODULE PG_INIT_GU_MULTIAREA__genmod
