        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE PG_INIT_AREA_GU_OSS__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_AREA_GU_OSS
            END SUBROUTINE PG_INIT_AREA_GU_OSS
          END INTERFACE 
        END MODULE PG_INIT_AREA_GU_OSS__genmod
