        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:34 2024
        MODULE PG_INITCASH_AREA__genmod
          INTERFACE 
            SUBROUTINE PG_INITCASH_AREA
            END SUBROUTINE PG_INITCASH_AREA
          END INTERFACE 
        END MODULE PG_INITCASH_AREA__genmod
