        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE PG_INIT_AREAPART_GEOM_XY__genmod
          INTERFACE 
            SUBROUTINE PG_INIT_AREAPART_GEOM_XY(X,Y)
              REAL(KIND=8) :: X(GSAREAPART%N)
              REAL(KIND=8) :: Y(GSAREAPART%N)
            END SUBROUTINE PG_INIT_AREAPART_GEOM_XY
          END INTERFACE 
        END MODULE PG_INIT_AREAPART_GEOM_XY__genmod
