        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:11 2024
        MODULE PG_REBUILD_BOUNDLINE__genmod
          INTERFACE 
            SUBROUTINE PG_REBUILD_BOUNDLINE(IBNDL,N0)
              INTEGER(KIND=4) :: IBNDL
              INTEGER(KIND=4) :: N0
            END SUBROUTINE PG_REBUILD_BOUNDLINE
          END INTERFACE 
        END MODULE PG_REBUILD_BOUNDLINE__genmod
