        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:37 2024
        MODULE PG_REBUILD_BOUNDLINE__genmod
          INTERFACE 
            SUBROUTINE PG_REBUILD_BOUNDLINE(IBNDL,N0)
              INTEGER(KIND=4) :: IBNDL
              INTEGER(KIND=4) :: N0
            END SUBROUTINE PG_REBUILD_BOUNDLINE
          END INTERFACE 
        END MODULE PG_REBUILD_BOUNDLINE__genmod
