        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:37 2024
        MODULE PG_REBUILD_BOUNDLINE_DS__genmod
          INTERFACE 
            SUBROUTINE PG_REBUILD_BOUNDLINE_DS(IBNDL,DS0)
              INTEGER(KIND=4) :: IBNDL
              REAL(KIND=8) :: DS0
            END SUBROUTINE PG_REBUILD_BOUNDLINE_DS
          END INTERFACE 
        END MODULE PG_REBUILD_BOUNDLINE_DS__genmod
