        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:25 2024
        MODULE PG_SOLVE_ITER__genmod
          INTERFACE 
            SUBROUTINE PG_SOLVE_ITER
            END SUBROUTINE PG_SOLVE_ITER
          END INTERFACE 
        END MODULE PG_SOLVE_ITER__genmod
