        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE PG_SET_AREACONST__genmod
          INTERFACE 
            SUBROUTINE PG_SET_AREACONST(J,VAL)
              INTEGER(KIND=4) :: J
              REAL(KIND=8) :: VAL
            END SUBROUTINE PG_SET_AREACONST
          END INTERFACE 
        END MODULE PG_SET_AREACONST__genmod
