        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:33 2024
        MODULE PG_SOLVE_BEGIN__genmod
          INTERFACE 
            SUBROUTINE PG_SOLVE_BEGIN
            END SUBROUTINE PG_SOLVE_BEGIN
          END INTERFACE 
        END MODULE PG_SOLVE_BEGIN__genmod
