        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:18 2024
        MODULE PG_SET_BOUNDLINE_GU_PANEL__genmod
          INTERFACE 
            SUBROUTINE PG_SET_BOUNDLINE_GU_PANEL(IGU,IUSE)
              INTEGER(KIND=4) :: IGU
              LOGICAL(KIND=4) :: IUSE(GSBNDL%NPANEL)
            END SUBROUTINE PG_SET_BOUNDLINE_GU_PANEL
          END INTERFACE 
        END MODULE PG_SET_BOUNDLINE_GU_PANEL__genmod
