        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE PG_SET_BOUNDLINE_GU_MODE__genmod
          INTERFACE 
            SUBROUTINE PG_SET_BOUNDLINE_GU_MODE(IBNDL,IMODE)
              INTEGER(KIND=4) :: IBNDL
              INTEGER(KIND=4) :: IMODE
            END SUBROUTINE PG_SET_BOUNDLINE_GU_MODE
          END INTERFACE 
        END MODULE PG_SET_BOUNDLINE_GU_MODE__genmod
