        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE PG_SOLVE_BEGIN__genmod
          INTERFACE 
            SUBROUTINE PG_SOLVE_BEGIN
            END SUBROUTINE PG_SOLVE_BEGIN
          END INTERFACE 
        END MODULE PG_SOLVE_BEGIN__genmod
