        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:25 2024
        MODULE PG_SET_MATRIX_N_ADD__genmod
          INTERFACE 
            SUBROUTINE PG_SET_MATRIX_N_ADD(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_SET_MATRIX_N_ADD
          END INTERFACE 
        END MODULE PG_SET_MATRIX_N_ADD__genmod
