        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE PG_SET_MATRIX_SPARSE_COUNT_CLOSING__genmod
          INTERFACE 
            SUBROUTINE PG_SET_MATRIX_SPARSE_COUNT_CLOSING(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_SET_MATRIX_SPARSE_COUNT_CLOSING
          END INTERFACE 
        END MODULE PG_SET_MATRIX_SPARSE_COUNT_CLOSING__genmod
