        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:41 2024
        MODULE PG_SET_INITIAL_APPROXSOLV__genmod
          INTERFACE 
            SUBROUTINE PG_SET_INITIAL_APPROXSOLV(F_IAS)
              REAL(KIND=8) :: F_IAS
              EXTERNAL F_IAS
            END SUBROUTINE PG_SET_INITIAL_APPROXSOLV
          END INTERFACE 
        END MODULE PG_SET_INITIAL_APPROXSOLV__genmod
