        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE PG_SET_MATRIX_N_ADD__genmod
          INTERFACE 
            SUBROUTINE PG_SET_MATRIX_N_ADD(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE PG_SET_MATRIX_N_ADD
          END INTERFACE 
        END MODULE PG_SET_MATRIX_N_ADD__genmod
