        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:08 2024
        MODULE PG_STOP_WRITE_LOG_FILE__genmod
          INTERFACE 
            SUBROUTINE PG_STOP_WRITE_LOG_FILE
            END SUBROUTINE PG_STOP_WRITE_LOG_FILE
          END INTERFACE 
        END MODULE PG_STOP_WRITE_LOG_FILE__genmod
