        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE PG_SOLVE_BEGIN__genmod
          INTERFACE 
            SUBROUTINE PG_SOLVE_BEGIN
            END SUBROUTINE PG_SOLVE_BEGIN
          END INTERFACE 
        END MODULE PG_SOLVE_BEGIN__genmod
