        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:41 2024
        MODULE PG_SOLVE__genmod
          INTERFACE 
            SUBROUTINE PG_SOLVE
            END SUBROUTINE PG_SOLVE
          END INTERFACE 
        END MODULE PG_SOLVE__genmod
