        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:16 2024
        MODULE PG_SET_EQ_VAR__genmod
          INTERFACE 
            SUBROUTINE PG_SET_EQ_VAR(EQ_VAR,N)
              INTEGER(KIND=4) :: N
              LOGICAL(KIND=4) :: EQ_VAR(N)
            END SUBROUTINE PG_SET_EQ_VAR
          END INTERFACE 
        END MODULE PG_SET_EQ_VAR__genmod
