        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE PG_SET_DOMAIN_EQUATION__genmod
          INTERFACE 
            SUBROUTINE PG_SET_DOMAIN_EQUATION(TYPE_EQ)
              INTEGER(KIND=4) :: TYPE_EQ
            END SUBROUTINE PG_SET_DOMAIN_EQUATION
          END INTERFACE 
        END MODULE PG_SET_DOMAIN_EQUATION__genmod
