        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE PREPARE_GLOBAL_SPARSEM__genmod
          INTERFACE 
            SUBROUTINE PREPARE_GLOBAL_SPARSEM
            END SUBROUTINE PREPARE_GLOBAL_SPARSEM
          END INTERFACE 
        END MODULE PREPARE_GLOBAL_SPARSEM__genmod
