        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE PREPARE_GLOBAL_SPARSEM__genmod
          INTERFACE 
            SUBROUTINE PREPARE_GLOBAL_SPARSEM
            END SUBROUTINE PREPARE_GLOBAL_SPARSEM
          END INTERFACE 
        END MODULE PREPARE_GLOBAL_SPARSEM__genmod
