        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:14 2024
        MODULE PRINT_PSI_OMEGA__genmod
          INTERFACE 
            SUBROUTINE PRINT_PSI_OMEGA
            END SUBROUTINE PRINT_PSI_OMEGA
          END INTERFACE 
        END MODULE PRINT_PSI_OMEGA__genmod
