        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:15 2024
        MODULE PRINT_FI_CONST__genmod
          INTERFACE 
            SUBROUTINE PRINT_FI_CONST(FI,G1)
              REAL(KIND=8) :: FI
              INTEGER(KIND=4) :: G1
            END SUBROUTINE PRINT_FI_CONST
          END INTERFACE 
        END MODULE PRINT_FI_CONST__genmod
