        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 12 23:25:44 2024
        MODULE PRINT_PSI_OMEGA__genmod
          INTERFACE 
            SUBROUTINE PRINT_PSI_OMEGA
            END SUBROUTINE PRINT_PSI_OMEGA
          END INTERFACE 
        END MODULE PRINT_PSI_OMEGA__genmod
