        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 26 11:02:20 2024
        MODULE PRINT_PSI_OMEGA__genmod
          INTERFACE 
            SUBROUTINE PRINT_PSI_OMEGA
            END SUBROUTINE PRINT_PSI_OMEGA
          END INTERFACE 
        END MODULE PRINT_PSI_OMEGA__genmod
