        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE PRINT_TOTAL_TIME__genmod
          INTERFACE 
            SUBROUTINE PRINT_TOTAL_TIME
            END SUBROUTINE PRINT_TOTAL_TIME
          END INTERFACE 
        END MODULE PRINT_TOTAL_TIME__genmod
