        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE PRINT_TOTAL_TIME__genmod
          INTERFACE 
            SUBROUTINE PRINT_TOTAL_TIME
            END SUBROUTINE PRINT_TOTAL_TIME
          END INTERFACE 
        END MODULE PRINT_TOTAL_TIME__genmod
