        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:11 2024
        MODULE REBUILD_BOUNDLINE__genmod
          INTERFACE 
            SUBROUTINE REBUILD_BOUNDLINE(IBNDL,DS0,N0,MODE)
              INTEGER(KIND=4) :: IBNDL
              REAL(KIND=8) :: DS0
              INTEGER(KIND=4) :: N0
              INTEGER(KIND=4) :: MODE
            END SUBROUTINE REBUILD_BOUNDLINE
          END INTERFACE 
        END MODULE REBUILD_BOUNDLINE__genmod
