        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:02 2024
        MODULE SB_INIT__genmod
          INTERFACE 
            SUBROUTINE SB_INIT
            END SUBROUTINE SB_INIT
          END INTERFACE 
        END MODULE SB_INIT__genmod
