        !COMPILER-GENERATED INTERFACE MODULE: Sun Dec 22 15:56:17 2024
        MODULE SEARCH_FOR_EXTREME_PARTICLES__genmod
          INTERFACE 
            FUNCTION SEARCH_FOR_EXTREME_PARTICLES
              REAL(KIND=8) :: SEARCH_FOR_EXTREME_PARTICLES
            END FUNCTION SEARCH_FOR_EXTREME_PARTICLES
          END INTERFACE 
        END MODULE SEARCH_FOR_EXTREME_PARTICLES__genmod
