        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE SET_DOMAIN_EQUATION__genmod
          INTERFACE 
            SUBROUTINE SET_DOMAIN_EQUATION(TYPE_EQ,TYPE_EQ2)
              INTEGER(KIND=4) :: TYPE_EQ
              INTEGER(KIND=4) :: TYPE_EQ2
            END SUBROUTINE SET_DOMAIN_EQUATION
          END INTERFACE 
        END MODULE SET_DOMAIN_EQUATION__genmod
