        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:15 2024
        MODULE SET_GA2_BASE__genmod
          INTERFACE 
            SUBROUTINE SET_GA2_BASE(GA)
              USE PGMOD
              TYPE (TBOUNLINEFUNCAPPROX) :: GA
            END SUBROUTINE SET_GA2_BASE
          END INTERFACE 
        END MODULE SET_GA2_BASE__genmod
