        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE SET_AA_CASH_INTEGRAL__genmod
          INTERFACE 
            SUBROUTINE SET_AA_CASH_INTEGRAL(IA,J,I,NF,VAL)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: NF
              REAL(KIND=8) :: VAL
            END SUBROUTINE SET_AA_CASH_INTEGRAL
          END INTERFACE 
        END MODULE SET_AA_CASH_INTEGRAL__genmod
