        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:26 2024
        MODULE SET_AB_CASH_INTEGRAL__genmod
          INTERFACE 
            SUBROUTINE SET_AB_CASH_INTEGRAL(IA,J,KND0,I,NF,VAL)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: J
              INTEGER(KIND=4) :: KND0
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: NF
              REAL(KIND=8) :: VAL
            END SUBROUTINE SET_AB_CASH_INTEGRAL
          END INTERFACE 
        END MODULE SET_AB_CASH_INTEGRAL__genmod
