        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE SPARSE_TO_M__genmod
          INTERFACE 
            SUBROUTINE SPARSE_TO_M
            END SUBROUTINE SPARSE_TO_M
          END INTERFACE 
        END MODULE SPARSE_TO_M__genmod
