        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE SPARSE_MEMORY__genmod
          INTERFACE 
            SUBROUTINE SPARSE_MEMORY(MODE)
              INTEGER(KIND=4) :: MODE
            END SUBROUTINE SPARSE_MEMORY
          END INTERFACE 
        END MODULE SPARSE_MEMORY__genmod
