        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE SPARSE_TO_M__genmod
          INTERFACE 
            SUBROUTINE SPARSE_TO_M
            END SUBROUTINE SPARSE_TO_M
          END INTERFACE 
        END MODULE SPARSE_TO_M__genmod
