        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 12 23:33:28 2024
        MODULE TESTING__genmod
          INTERFACE 
            SUBROUTINE TESTING
            END SUBROUTINE TESTING
          END INTERFACE 
        END MODULE TESTING__genmod
