        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE TEST_M_DIAGONAL__genmod
          INTERFACE 
            SUBROUTINE TEST_M_DIAGONAL
            END SUBROUTINE TEST_M_DIAGONAL
          END INTERFACE 
        END MODULE TEST_M_DIAGONAL__genmod
