        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:17 2024
        MODULE TEST_INTL__genmod
          INTERFACE 
            SUBROUTINE TEST_INTL
            END SUBROUTINE TEST_INTL
          END INTERFACE 
        END MODULE TEST_INTL__genmod
