        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:17 2024
        MODULE TEST_INTD__genmod
          INTERFACE 
            SUBROUTINE TEST_INTD
            END SUBROUTINE TEST_INTD
          END INTERFACE 
        END MODULE TEST_INTD__genmod
