        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:29 2024
        MODULE TEST_INVERT_TRM__genmod
          INTERFACE 
            SUBROUTINE TEST_INVERT_TRM(IPART)
              INTEGER(KIND=4) :: IPART
            END SUBROUTINE TEST_INVERT_TRM
          END INTERFACE 
        END MODULE TEST_INVERT_TRM__genmod
