        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 02 20:31:40 2024
        MODULE TESTING__genmod
          INTERFACE 
            SUBROUTINE TESTING
            END SUBROUTINE TESTING
          END INTERFACE 
        END MODULE TESTING__genmod
