        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE TEST_MATR_MAXMINCOL__genmod
          INTERFACE 
            SUBROUTINE TEST_MATR_MAXMINCOL
            END SUBROUTINE TEST_MATR_MAXMINCOL
          END INTERFACE 
        END MODULE TEST_MATR_MAXMINCOL__genmod
