        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:09 2024
        MODULE TEST_AREA_GU__genmod
          INTERFACE 
            FUNCTION TEST_AREA_GU(K)
              INTEGER(KIND=4) :: K
              LOGICAL(KIND=4) :: TEST_AREA_GU
            END FUNCTION TEST_AREA_GU
          END INTERFACE 
        END MODULE TEST_AREA_GU__genmod
