        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:11 2024
        MODULE TEST_INVERT_TRM__genmod
          INTERFACE 
            SUBROUTINE TEST_INVERT_TRM(IPART)
              INTEGER(KIND=4) :: IPART
            END SUBROUTINE TEST_INVERT_TRM
          END INTERFACE 
        END MODULE TEST_INVERT_TRM__genmod
