        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:37 2024
        MODULE TEST_CP_CINT2__genmod
          INTERFACE 
            SUBROUTINE TEST_CP_CINT2
            END SUBROUTINE TEST_CP_CINT2
          END INTERFACE 
        END MODULE TEST_CP_CINT2__genmod
