        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE TEST_MATR_MAXMINCOL__genmod
          INTERFACE 
            SUBROUTINE TEST_MATR_MAXMINCOL
            END SUBROUTINE TEST_MATR_MAXMINCOL
          END INTERFACE 
        END MODULE TEST_MATR_MAXMINCOL__genmod
