        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:33 2024
        MODULE TEST_CLOSING_SLAU__genmod
          INTERFACE 
            SUBROUTINE TEST_CLOSING_SLAU
            END SUBROUTINE TEST_CLOSING_SLAU
          END INTERFACE 
        END MODULE TEST_CLOSING_SLAU__genmod
