        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE TEST_MATR_MAXMINCOL__genmod
          INTERFACE 
            SUBROUTINE TEST_MATR_MAXMINCOL
            END SUBROUTINE TEST_MATR_MAXMINCOL
          END INTERFACE 
        END MODULE TEST_MATR_MAXMINCOL__genmod
