        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:13 2024
        MODULE TEST_CP_CINT2__genmod
          INTERFACE 
            SUBROUTINE TEST_CP_CINT2
            END SUBROUTINE TEST_CP_CINT2
          END INTERFACE 
        END MODULE TEST_CP_CINT2__genmod
