        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE TEST_CLOSING_SLAU__genmod
          INTERFACE 
            SUBROUTINE TEST_CLOSING_SLAU
            END SUBROUTINE TEST_CLOSING_SLAU
          END INTERFACE 
        END MODULE TEST_CLOSING_SLAU__genmod
