        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:37 2024
        MODULE TEST_CP_CINT__genmod
          INTERFACE 
            SUBROUTINE TEST_CP_CINT
            END SUBROUTINE TEST_CP_CINT
          END INTERFACE 
        END MODULE TEST_CP_CINT__genmod
