        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:25 2024
        MODULE TEST_INTD__genmod
          INTERFACE 
            SUBROUTINE TEST_INTD
            END SUBROUTINE TEST_INTD
          END INTERFACE 
        END MODULE TEST_INTD__genmod
