        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:38 2024
        MODULE TEST_INTL__genmod
          INTERFACE 
            SUBROUTINE TEST_INTL
            END SUBROUTINE TEST_INTL
          END INTERFACE 
        END MODULE TEST_INTL__genmod
