        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:13 2024
        MODULE TEST_CP_CINT__genmod
          INTERFACE 
            SUBROUTINE TEST_CP_CINT
            END SUBROUTINE TEST_CP_CINT
          END INTERFACE 
        END MODULE TEST_CP_CINT__genmod
