        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 26 11:33:42 2024
        MODULE TESTING__genmod
          INTERFACE 
            SUBROUTINE TESTING
            END SUBROUTINE TESTING
          END INTERFACE 
        END MODULE TESTING__genmod
