        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:41 2024
        MODULE TEST_CLOSING_SLAU__genmod
          INTERFACE 
            SUBROUTINE TEST_CLOSING_SLAU
            END SUBROUTINE TEST_CLOSING_SLAU
          END INTERFACE 
        END MODULE TEST_CLOSING_SLAU__genmod
