        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE TEST_M_DIAGONAL__genmod
          INTERFACE 
            SUBROUTINE TEST_M_DIAGONAL
            END SUBROUTINE TEST_M_DIAGONAL
          END INTERFACE 
        END MODULE TEST_M_DIAGONAL__genmod
