        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:25 2024
        MODULE TEST_INTL__genmod
          INTERFACE 
            SUBROUTINE TEST_INTL
            END SUBROUTINE TEST_INTL
          END INTERFACE 
        END MODULE TEST_INTL__genmod
