        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE WRITE_MATR__genmod
          INTERFACE 
            SUBROUTINE WRITE_MATR
            END SUBROUTINE WRITE_MATR
          END INTERFACE 
        END MODULE WRITE_MATR__genmod
