        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:32 2024
        MODULE WRITE_MATR_B__genmod
          INTERFACE 
            SUBROUTINE WRITE_MATR_B
            END SUBROUTINE WRITE_MATR_B
          END INTERFACE 
        END MODULE WRITE_MATR_B__genmod
