        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE WRITE_MATR_B__genmod
          INTERFACE 
            SUBROUTINE WRITE_MATR_B
            END SUBROUTINE WRITE_MATR_B
          END INTERFACE 
        END MODULE WRITE_MATR_B__genmod
