        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:33 2024
        MODULE WRITE_BY_TIMEF__genmod
          INTERFACE 
            FUNCTION WRITE_BY_TIMEF(STR)
              CHARACTER(*) :: STR
              LOGICAL(KIND=4) :: WRITE_BY_TIMEF
            END FUNCTION WRITE_BY_TIMEF
          END INTERFACE 
        END MODULE WRITE_BY_TIMEF__genmod
