        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE WRITE_BY_TIME__genmod
          INTERFACE 
            SUBROUTINE WRITE_BY_TIME(STR)
              CHARACTER(*) :: STR
            END SUBROUTINE WRITE_BY_TIME
          END INTERFACE 
        END MODULE WRITE_BY_TIME__genmod
