        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE WRITE_MATR__genmod
          INTERFACE 
            SUBROUTINE WRITE_MATR
            END SUBROUTINE WRITE_MATR
          END INTERFACE 
        END MODULE WRITE_MATR__genmod
