        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 09 10:15:24 2024
        MODULE WRITE_MATRIX_MM__genmod
          INTERFACE 
            SUBROUTINE WRITE_MATRIX_MM
            END SUBROUTINE WRITE_MATRIX_MM
          END INTERFACE 
        END MODULE WRITE_MATRIX_MM__genmod
