        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:33 2024
        MODULE WRITE_BY_TIMEF2__genmod
          INTERFACE 
            FUNCTION WRITE_BY_TIMEF2(STR,TEST)
              CHARACTER(*) :: STR
              LOGICAL(KIND=4) :: TEST
              LOGICAL(KIND=4) :: WRITE_BY_TIMEF2
            END FUNCTION WRITE_BY_TIMEF2
          END INTERFACE 
        END MODULE WRITE_BY_TIMEF2__genmod
