        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE WRITE_MATR__genmod
          INTERFACE 
            SUBROUTINE WRITE_MATR
            END SUBROUTINE WRITE_MATR
          END INTERFACE 
        END MODULE WRITE_MATR__genmod
