        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 16 21:00:40 2024
        MODULE WRITE_MATR_B__genmod
          INTERFACE 
            SUBROUTINE WRITE_MATR_B
            END SUBROUTINE WRITE_MATR_B
          END INTERFACE 
        END MODULE WRITE_MATR_B__genmod
