        !COMPILER-GENERATED INTERFACE MODULE: Sat Dec 07 19:21:05 2024
        MODULE WRITE_ITER_EMPTY__genmod
          INTERFACE 
            FUNCTION WRITE_ITER_EMPTY(STR,TEST)
              CHARACTER(*) :: STR
              LOGICAL(KIND=4) :: TEST
              LOGICAL(KIND=4) :: WRITE_ITER_EMPTY
            END FUNCTION WRITE_ITER_EMPTY
          END INTERFACE 
        END MODULE WRITE_ITER_EMPTY__genmod
